### ISSUE TITLE
Overriding test.client.parameters for HTTP_HOST does not work with WebTestCase

### ISSUE THREAD

**Issue by adrienbrault** [symfony/symfony#12189]
Hi,

I've tried to override the test client `HTTP_HOST` server param in my app config:

```yaml
parameters:
    test.client.parameters:
        HTTP_HOST: symfony.com
```

However, in functional tests (WebTestCase), `$client->getServerParameter('HTTP_HOST')` does not return `symfony.com` but the default `localhost`.

The client is actually correctly configured at https://github.com/symfony/symfony/blob/cf3cd9578c29b77185bb701b4fc789ad4872ec84/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L35

but the call on the next line `$client->setServerParameters($server);` with an empty array erases `HTTP_HOST` because of the method definition: https://github.com/symfony/symfony/blob/cf3cd9578c29b77185bb701b4fc789ad4872ec84/src/Symfony/Component/BrowserKit/Client.php#L113-L119

**Comment by stayeronglass** [comment]
any progress?

**Comment by jakzal** [comment]
should be fixed by #16265

**Comment by aistis-** [comment]
Does anyone face the same problem with other parameters?

```
# config_test.yml
...
parameters:
    test.client.parameters:
        HTTPS: true
```

**Comment by MacDada** [comment]
That's still an issue when using a default WebTestCase:

```
# services_test.yml
parameters:
    test.client.parameters:
        HTTP_HOST: 'example.dev'
```

The config works and in the `Client` constructor the host is being configured: https://github.com/symfony/symfony/blob/v3.4.45/src/Symfony/Component/BrowserKit/Client.php#L55

BUT, WebTestCase overrides it: https://github.com/symfony/symfony/blob/v3.4.45/src/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php#L45

And that forces me to override WebTestCase and set proper host manually instead of depending on config.

---

Possible solution: https://github.com/symfony/symfony/pull/20535 – it was a good one – overriding just the parameters that are needed, not all of them.

There was a concern about BC, but it can be handled: https://github.com/symfony/symfony/pull/20535#issuecomment-265139264

I can make a new PR if this is acceptable solution.

**Comment by MacDada** [comment]
Where should I add test for that? Maybe here? https://github.com/symfony/symfony/blob/v3.4.45/src/Symfony/Bundle/FrameworkBundle/Tests/ClientTest.php
