### ISSUE TITLE
[2.8] Deprecation notice when using factory_service/factory_method 

### ISSUE THREAD

**Issue by iltar** [symfony/symfony#14687]
Starting on a PR regarding another issue and I hooked up on of my applications to 2.8 instead of 2.6. For me this was 2 seconds to figure out it was caused by the old way of defining a factory service + method, but the error message might cause a lot of confusion for others. The message is thrown in the Definition class rather than the place where you expect it (Yaml Loader in this case).

The fix for this is to change your service definition:

```yml
    # old
    app.layout.menu.beta:
        class: Knp\Menu\MenuItem
        factory_service: app.layout.menu_builder
        factory_method: createBetaMenu
        tags:
            - { name: knp_menu.menu, alias: beta }

    # new
    app.layout.menu.beta:
        class: Knp\Menu\MenuItem
        factory: [@app.layout.menu_builder, createBetaMenu]
        tags:
            - { name: knp_menu.menu, alias: beta }
```

The thing is that the error message below does not clearly reflect that. I don't think it's desired to put this information in the message below, but maybe someone has a nice idea where to put it instead.

```
Deprecated: The Symfony\Component\DependencyInjection\Definition::setFactoryMethod method is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. in /home/ivanderberg/projects/symfony/src/Symfony/Component/DependencyInjection/Definition.php on line 137
```

**Comment by xabbuh** [comment]
To get a more sensible deprecation message, we will have to trigger them in the loader classes. However, this would mean that one one get two messages, one from the loader and one from the `Definition` class.

I see two solutions to get rid of the double message:

* Add an argument to optionally silence the deprecated method (we did that in some other places where we didn't have another option for internal code).
* Stop the loaders from using `setFactoryClass()`, `setFactoryService()` and `setFactoryMethod()` and let them call `setFactory()` instead regardless of how the user configured the factory. Will that solution have any downsides?

**Comment by Tobion** [comment]
Just add to the deprecation message in the Definition that it could also be caused by using `factory_service` and `factory_method` in configuration file.

**Comment by iltar** [comment]
Another question related to this though, I have fixed all my application usages, but composer is still complaining. I suspect this is coming from a third-party bundle, but I am not sure which or where just yet.

The problem is that I can't suppress those warnings in composer and it will cause a deployment failure on the `cache:warmup`. Any tips on that issue?

**Comment by xabbuh** [comment]
@Tobion Though you would still not know which file actually causes the issue. Given that the warning can also be triggered by a third-party bundle, this could become hard to debug imho.

**Comment by Tobion** [comment]
@xabbuh true

**Comment by stof** [comment]
@xabbuh calling ``setFactory`` is not an option, because it would force to have a service definition defining the whole factory at once, while the old syntax allows that (think about a service overwriting only part of the factory compared to the parent)

**Comment by eXtreme** [comment]
I had similar problems as @iltar with composer/warmup spamming with deprecations  - afair it was caused by sonata admin dependency and as a quick fix I placed `error_reporting(E_ALL & ~E_USER_DEPRECATED & ~E_DEPRECATED);` in the constructor of my kernel.

**Comment by gnutix** [comment]
Same issue here using bowerphp:

```
Script php vendor/bin/bowerphp install handling the post-update-cmd event returned with an error

PHP Fatal error:  Uncaught exception 'ErrorException' with message '"Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console\Helper\QuestionHelper" instead.' in /vagrant/vendor/symfony/symfony/src/Symfony/Component/Console/Helper/DialogHelper.php:34
```

**Comment by nicolas-grekas** [comment]
Having better error messages would be great, even in 2.7.x releases IMO. I wouldn’t mind the duplicate too much.

**Comment by xabbuh** [comment]
see #14798

**Comment by gnutix** [comment]
Is there a way to filter the deprecation messages that comes from the application code (`src/`) and not 3rd-party code (`vendor/`) ?
