### ISSUE TITLE
Why uses the event dispatcher call_user_func

### ISSUE THREAD

**Issue by dawehner** [symfony/symfony#15313]
Maybe I'm blind but is there a reason why the event dispatcher can't just use a direct method call instead of using call_user_func?

**Comment by iltar** [comment]
I assume you're talking about this? https://github.com/symfony/symfony/blob/4133aadd0c0be199b21ce5e171038e5d03bc818b/src/Symfony/Component/EventDispatcher/EventDispatcher.php#L165-L173

```php
$listener($event, $eventName, $this);
```
It's possible, but I don't know why it's not done like this. Perhaps older PHP Versions?

**Comment by xabbuh** [comment]
This is need to support PHP 5.3 (see, for example, http://3v4l.org/hr7le).

**Comment by stof** [comment]
And even on PHP 5.4+, ``$listener()`` does not work for all types of callables. PHP 5.4 added support for *most* kind of callables, but it missed one.

**Comment by iltar** [comment]
How far would PHP 5.5 be supporting this? For the master (3.0) this could be supported.

**Comment by jvasseur** [comment]
The one not supported by PHP 5.4+ is a callback in the form ```'EventListener::onEvent'```, it is only fixed in php 7 (http://3v4l.org/SjSJN).

**Comment by stof** [comment]
@iltar PHP 5.6 and even PHP 7 still don't allow calling all callables this way, which is exactly why we still use ``call_user_func`` and ``call_user_func_array`` in master (@nicolas-grekas already checked all places where we could safely stop using it)

**Comment by stof** [comment]
ah looks like PHP 7 actually fixed it. yeah!

**Comment by dawehner** [comment]
Ah cool. Great to know. Thank yoU!

**Comment by nicolas-grekas** [comment]
https://bugs.php.net/bug.php?id=68475
