### ISSUE TITLE
Validator erroneously merges constraints from overriden properties

### ISSUE THREAD

**Issue by eggyal** [symfony/symfony#15950]
A simple example—

``` php
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Validation;
use Doctrine\Common\Annotations\AnnotationRegistry;

AnnotationRegistry::registerAutoloadNamespace('Symfony\Component\Validator\Constraints', __DIR__);

class Parent
{
    /**
     * @Assert\EqualTo(0)
     */
    public $example = 0;
}

class Child extends Parent
{
    /**
     * @Assert\EqualTo(1)
     */
    public $example = 1;    // overrides parent property of same name
}

echo Validation::createValidatorBuilder()
               ->enableAnnotationMapping()
               ->getValidator()
               ->validate(new Child());
```

The validation fails because the constraint that was defined on `Parent::$example` has been merged with that for `Child::$example` (and, in this case, they are mutually exclusive).

This cannot be right—the child property has completely replaced that of the parent and all of the latter's metadata (including validation constraints) should be discarded.

For the time being, I have added the following two lines after [`AnnotationLoader.php:61`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Validator/Mapping/Loader/AnnotationLoader.php#L61):

``` php
                unset($metadata->members[$property->name]);
                unset($metadata->properties[$property->name]);
```

However, I acknowledge that this is horrible—at very least, `ClassMetadata` should provide a method for resetting a property, but even if one could use that I'm not familiar enough with the code to be certain that this approach doesn't break something else.  Grateful for your thoughts!

**Comment by iltar** [comment]
Would this not be simply solved by making your properties private or is this bugged in the same fashion?

**Comment by eggyal** [comment]
@iltar: No, the bug persists even if the properties are private; indeed, that is my actual use-case (I only used public properties above to simplify the example).

**Comment by xabbuh** [comment]
related to #15582?

**Comment by xabbuh** [comment]
see #21053

**Comment by xabbuh** [comment]
I am reopening here as we reverted #21053 which broke BC (see #21538, #21567, and #21592).

**Comment by HeahDude** [comment]
@xabbuh My guess is that the expected behavior of an inherited property should be either:

 - define no assertion => as you said "agree with @ro0NL on https://github.com/symfony/symfony/issues/21567#issuecomment-278729990,

 - define some other assertions => merge them all,

 - redefine an inherited assertion => the new override the inherited,

What do you think?

**Comment by mvrhov** [comment]
I'd say if none is defined in child then inherit. If at least one is defined then all needed should be defined, otherwise there is no way to remove some from the parent.

Or even better add private/protected property to each validation. Where the behavior would be the same as in class inheritance. private parent only, protected parent+child. However this doesn't allow you to override the validators in 3rd party bundles.

**Comment by ro0NL** [comment]
> otherwise there is no way to remove some from the parent

IMO. this is a non-issue.. create a new domain (class/property) then. It's weird to say "*extend* this definition, but dont extend this specific thingy". It doesnt reflect class extending.

> redefine an inherited assertion => the new overrides the inherited and keep the others

Probably makes sense for most constraints; for `Callback` and `Not*` constraints it can be confusing.

Last but not least; there can be conflicts (parent defines `NotBlank`, child defines `Blank`), i tend to qualify it as a design flaw (you should not do it).

**Comment by xabbuh** [comment]
> I'd say if none is defined in child then inherit. If at least one is defined then all needed should be defined, otherwise there is no way to remove some from the parent.

I think this would be the easiest to explain approach and one that would probably cause the least confusion. However, this will very likely break existing applications so IMO cannot be done before 4.0 (and then, what would be the way to deprecate the current behaviour?).

> redefine an inherited assertion => the new overrides the inherited and keep the others,

This one is probably the easiest to implement with the current code base and the current behaviour of it. Though it still bares some potential for conflicts with existing constraints that negate each other as @ro0NL pointed out.

What does the Java spec say about this case? Is anyone willing to look that up so we can see if that sheds some light on the issue?

**Comment by Maxooo** [comment]
2 years and several Symfony versions later the issue is still open.

**Comment by engharb** [comment]
Hi,

I still facing problem mentioned in 'Validation Constraint Inheritance Broken #21567'. the symfony v: 4.1 Do you have any idea how to fix it?

**Comment by rjwebdev** [comment]
I'm having the same issue. I defined a class `AbstractAddress` with following property:
```

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=5)
     *
     * @Assert\NotBlank(groups={"Address"})
     */
    protected $houseNumber;
```
`AbstractAddress` is extended by an `Address` class, which is used in a form and as a nested member of my `User` class:
```

    /**
     * @var Address
     *
     * @Assert\Valid(groups={"Default", "Addres"})
     */
    private $privateAddress;
```

When I define the validation groups on a form used to edit my user object, nothing happens with the validation of my `privateAddress` property if I don't fill in the houseNumber field in my form. Any idea on how to solve this?

**Comment by xabbuh** [comment]
Is that a mistake when copying the code or is the validation group in the second code block indeed different from the one in the first code block (`Address` vs. `Addres`)?

**Comment by rjwebdev** [comment]
Wow @xabbuh ,

Didn't noticed that at all! Thank you and sorry for the wrong information

**Comment by florianbelhomme** [comment]
I'm not sure of the expected behavior. The validator have the 2 constraints for the property.

```
dd($validator->getMetadataFor(new MyChild())->getPropertyMetadata('example'));

array:2 [
    0 => Symfony\Component\Validator\Mapping\PropertyMetadata^ {#20
    +class: "MyChild"
    +name: "example"
    +property: "example"
    -reflMember: []
    +constraints: array:1 [
        0 => Symfony\Component\Validator\Constraints\EqualTo^ {#26
        +message: "This value should be equal to {{ compared_value }}."
        +value: 1
        +propertyPath: null
        +payload: null
        +"groups": array:2 [
            0 => "Default"
          1 => "MyChild"
        ]
      }
    ]
    +constraintsByGroup: array:2 [
        "Default" => array:1 [
        0 => Symfony\Component\Validator\Constraints\EqualTo^ {#26}
        ]
        "MyChild" => array:1 [
            0 => Symfony\Component\Validator\Constraints\EqualTo^ {#26}
            ]
            ]
            +cascadingStrategy: 1
            +traversalStrategy: 2
  }
  1 => Symfony\Component\Validator\Mapping\PropertyMetadata^ {#24
            +class: "MyParent"
            +name: "example"
            +property: "example"
            -reflMember: array:1 [
                "MyChild" => ReflectionProperty {#30
                +name: "example"
                +class: "MyChild"
        modifiers: "public"
        extra: {
                    docComment: """
            /**\n
                 * @Assert\EqualTo(1)\n
                 */
            """
        }
      }
    ]
    +constraints: array:1 [
                0 => Symfony\Component\Validator\Constraints\EqualTo^ {#28
                +message: "This value should be equal to {{ compared_value }}."
                +value: 0
                +propertyPath: null
                +payload: null
                +"groups": array:3 [
                    0 => "Default"
          1 => "MyParent"
          2 => "MyChild"
        ]
      }
    ]
    +constraintsByGroup: array:3 [
                "Default" => array:1 [
                0 => Symfony\Component\Validator\Constraints\EqualTo^ {#28}
                ]
                "MyParent" => array:1 [
                    0 => Symfony\Component\Validator\Constraints\EqualTo^ {#28}
                    ]
                    "MyChild" => array:1 [
                        0 => Symfony\Component\Validator\Constraints\EqualTo^ {#28}
                        ]
                        ]
                        +cascadingStrategy: 1
                        +traversalStrategy: 2
  }
]
```

**Comment by greedyivan** [comment]
> What does the Java spec say about this case? Is anyone willing to look that up so we can see if that sheds some light on the issue?

> The effect of constraint declarations is cumulative. Constraints declared on a superclass getter will be validated along with any constraints defined on an overridden version of the getter according to the Java Language Specification visibility rules.
-- [3.3. Inheritance (interface and superclass)](https://beanvalidation.org/1.0/spec/#constraintdeclarationvalidationprocess-inheritance)

An effect other than cumulative will violate the Liskov substitution principle.

This may not be a bug at all, but requires some clarification in the documentation on constraint inheritance.

**Comment by michaelKaefer** [comment]
@xabbuh Can you please remove the "Help wanted" label? (I think help was wanted to look up the Java spec, or?)

(So the Java spec just says that in general constraint declarations are cumulative, it does not say anything on conflicting constraint overrides explicitly)

**Comment by xabbuh** [comment]
I am afraid we cannot really touch this part of the code. Let's ensure instead to document this properly. That's why I have opened symfony/symfony-docs#14784. Closing here now.
