### ISSUE TITLE
[DoctrineBridge] Use parameter in tag for doctrine.event_listener

### ISSUE THREAD

**Issue by jewome62** [symfony/symfony#16239]
Hello,

Environement : Symfony 2.7.3, Doctrine ORM 2.5

I created a bundle that must be configured on the choice of the database
I need add a parameter for choose the database in project's configuration.

``` yaml
services:
    jewome62_author.doctrine.listener.personal_data:
        class: Jewome62\AuthorBundle\Listener\PersonalDataListener
        tags: 
            - { name: doctrine.event_listener, event: postLoad, connection: %jewome62_author.connection_name% }
            - { name: doctrine.event_listener, event: prePersist, connection: %jewome62_author.connection_name% }
            - { name: doctrine.event_listener, event: preUpdate, connection: %jewome62_author.connection_name% }
```

I write valid bundle configuration. But when I try anything (console or web) 
I have this error : 

``` console

  [RuntimeException]                                                                                                                                                     
  The Doctrine connection "%jewome62_author.connection_name%" referenced in service "jewome62_author.doctrine.listener.personal_data" does not exist. Available con  
  nections names: default, customer                                                                                                                                      



Exception trace:
 () at /var/www/project/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php:131
 Symfony\Bridge\Doctrine\DependencyInjection\CompilerPass\RegisterEventListenersAndSubscribersPass->groupByConnection() at /var/www/project/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/DependencyInjection/CompilerPass/RegisterEventListenersAndSubscribersPass.php:89
 Symfony\Bridge\Doctrine\DependencyInjection\CompilerPass\RegisterEventListenersAndSubscribersPass->process() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:614
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /var/www/project/var/bootstrap.php.cache:2633
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /var/www/project/var/bootstrap.php.cache:2411
 Symfony\Component\HttpKernel\Kernel->boot() at /var/www/project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /var/www/project/bin/console:27
```

I feel that the interpretation of the parameters is not do for tags.
It's a normal ? a bug ? a feature ?

Do you have any idea to make the configurable connection for the event listener?

Thanks

**Comment by piotrkochan** [comment]
Same problem

**Comment by Tobion** [comment]
You can write your own DI compiler pass that resolves parameters.

**Comment by Tobion** [comment]
But according to http://image.slidesharecdn.com/new-symfony-tips-and-tricks-151208075102-lva1-app6891/95/new-symfony-tips-tricks-symfonycon-paris-2015-108-638.jpg?cb=1449561686 parameters in tags are resolved (at least for monolog tag). So either it should work or it's missing for the doctrine.event_listener tag.

**Comment by stof** [comment]
@Tobion they are not resolved generally. MonologBundle 2.8 resolves parameters in channel names

**Comment by javiereguiluz** [comment]
@xabbuh you've committed several changes related to DependencyInjection lately. What do you think about the idea of generalizing the support of container parameters as the values of service tags parameters? Thanks.

**Comment by xabbuh** [comment]
Even if it may be tempting to generally resolve parameters for tags, I don't see how we could do that in a backwards compatible way as people can rely on the fact that parameters are not resolved when dealing with tags in their custom compiler passes.

**Comment by ogizanagi** [comment]
I've created https://github.com/symfony/symfony/pull/20834 in case this is at least something useful for the `connection` attribute.

**Comment by stof** [comment]
even this may not be BC (as connection names can be any string)

**Comment by ogizanagi** [comment]
@stof : Agree, but it's unlikely to have a connection named `%something%`.
