### ISSUE TITLE
[Form][2.7] - Incorrect type casting in ChoiceToValueTransformer?

### ISSUE THREAD

**Issue by Ranmus** [symfony/symfony#16303]
Hi,

I try to generate entity type field that will be select input in html with single choice. Additionaly it must contain an empty option to choose for setting reference entity to null, so i define 'placeholder' with some message and 'empty_data' set to null. Form field is generated correctly, but when i select an empty option and submit form, Symfony throws an exception like below:
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: ""

But if i switch field from select to radios via options 'expanded' = true, then empty option is treated correctly and form can be submitted with no errors. So i searched what cause above exception and found this in ChoiceToValueTransformer.php:

`$choices = $this->choiceList->getChoicesForValues(array($value));`

And when `$value` is an integer with id of entity, like `10`, it is converted to `[10]`. But when `$value` is null, then result of conversion is `['']` causing exception.

Isn't should be like this:
`$choices = $this->choiceList->getChoicesForValues(array( $value ? (string) $value : null ));`

So when `$value` is null then result is `[null]` and all is working fine.

**Comment by stof** [comment]
which version of Symfony are you using ? The case of integer should already be fixed

**Comment by LukaszStrzyzowski** [comment]
Symfony 2.7.1. Hmmm..., i will check most recent version.

**Comment by LukaszStrzyzowski** [comment]
I've checked last version of 2.7.x and 2.8. Problem still persists.

**Comment by xabbuh** [comment]
Can you fork the Symfony Standard Edition and make the minimum needed set of changes to reproduce your issue?

**Comment by Ranmus** [comment]
I'm sorry, but i didn't checked precisely. This problem was already fixed here: https://github.com/symfony/symfony/commit/d209d1c35aa6219611b8d2b815f5485f5ea6e224

Issue can be closed.
