### ISSUE TITLE
[Yaml] colon inside comment

### ISSUE THREAD

**Issue by benji07** [symfony/symfony#16784]
I got an error after updating to symfony3

> A colon cannot be used in an unquoted mapping value.
> at Parser->parseValue('true # default: false', false, false, false, 'mapping') in Parser.php line 231

```yml
elao_error_notifier:
    handle404: true # default: false
```

**Comment by Tischoi** [comment]
This was fixed in #16745 (2.8) but was somehow not merged into 3.0.

**Comment by derrabus** [comment]
Strange, github says that the commit is included in the v2.8.0 and v3.0.0 tags.

<img width="550" alt="bildschirmfoto 2015-12-01 um 16 41 39" src="https://cloud.githubusercontent.com/assets/1506493/11505397/7e1bcca2-984a-11e5-8ca2-ed68c9378ec5.png">

ping @xabbuh

**Comment by stof** [comment]
@derrabus the commit is included, but conflicts have been resolved the wrong way, leading to loosing the bugfix in 3.0. I already have it passing again locally

**Comment by matthbull** [comment]
Im still getting this error on 2.8. Not sure if thats expected, but looking at this thread it doesnt seem so.

> [Symfony\Component\Yaml\Exception\ParseException]                                                                                     
  A colon cannot be used in an unquoted mapping value at line 72 (near "check_email: Изпратихме писмо с линк за активация на посочения  
   E-mail адрес: %email%. Ако не откривате писмото проверете и в папка СПАМ."). 

*Filename: FOSUserBundle.bg.yml*
```
resetting:
    password_already_requested: Този потребител вече е поискал смяна на парола в последните 24 часа.
    check_email: Изпратихме писмо с линк за активация на посочения E-mail адрес: %email%. Ако не откривате писмото проверете и в папка СПАМ.
```

**Comment by benji07** [comment]
@matthbull you got a colon just after "адрес"

You need to quote the whole line

```
resetting:
    password_already_requested: Този потребител вече е поискал смяна на парола в последните 24 часа.
    check_email: "Изпратихме писмо с линк за активация на посочения E-mail адрес: %email%. Ако не откривате писмото проверете и в папка СПАМ."

**Comment by silverjebs** [comment]
Hi, i was getting it from a comment in config.xml in 2.8 while running phpunit... solved thanks to this issue :)
<pre>
fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
</pre>

**Comment by matthbull** [comment]
@benji07 yes, I know it needs quoting, but its in a vendor bundle so I cant.  And seeing as it seems to be the same initial issue I thought Id mention it.

**Comment by xabbuh** [comment]
@matthbull Looks like this was fixed in FOSUserBundle with FriendsOfSymfony/FOSUserBundle#1990.
