### ISSUE TITLE
[Debug] PHP 7 Error Exceptions logged twice

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony#16980]
With PHP 7, `\Error` exceptions are logged two times as critical.
Here an example of the `TypeEror`.

> - CRITICAL - Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Request::getPreferredLanguage() must be of the type array, string given, called in src\AppBundle\Controller\DefaultController.php on line 17 
> - CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Request::getPreferredLanguage() must be of the type array, string given, called in src\AppBundle\Controller\DefaultController.php on line 17" at src\Symfony\Component\HttpFoundation\Request.php line 1535 

The reason for this is that the `ErrorHandler::handleException` logs the PHP error exception. It than wraps the Throwable in a `FatalThrowableError` to let the Kernel exception listeners do their work (which are typehinted against `\Exception`, see `GetResponseForExceptionEvent`). Then the `ExceptionListener` kicks in, which logs the `FatalThrowableError` again.

One error should not cause multiple error logs. Also the second error log with `Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError` is kinda wrong/irritating because you cannot actually catch the `FatalThrowableError`. You have to catch the `\Error` or `\Throwable` instead.

This double logging is in dev environment. In prod env only the second wrong error "Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError" is logged.

**Comment by nicolas-grekas** [comment]
So, when an exception/error is re-injected to the kernel via terminateWithException, we should display it but not log it, knowing that the error handler already had a chance to lg it (and thus did so). Right?

**Comment by nicolas-grekas** [comment]
So, when an exception/error is re-injected to the kernel via terminateWithException, we should display it but not log it, knowing that the error handler already had a chance to lg it (and thus did so). Right?

**Comment by Tobion** [comment]
That would be the first step yes.

**Comment by nicolas-grekas** [comment]
The exception is logged on two different channels (php and request). Do you think it matter? We should only log on the php one then?

**Comment by yapro** [comment]
Yes, you should log Fatal error only once. I don't want to see the same error 2 times, it only clogs up the logs. Thank you.

**Comment by nicolas-grekas** [comment]
Should be fixed by #17202, could you please confirm?

**Comment by Tobion** [comment]
This problem seems to be back again using Symfony 3.3. I get two critical error logs for the same thing.

>CRITICAL php Type error: ...
 CRITICAL request	Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: ...

**Comment by Tobion** [comment]
@nicolas-grekas the problem is still there with SE 3.4 rc2

**Comment by nicolas-grekas** [comment]
Fixed in #25408

**Comment by gigi** [comment]
Can You please check current status?
Seems problem came back again...
Symfony 4.0.8
```
[2018-04-27 12:41:55] app.CRITICAL: Unhandled exception...
[2018-04-27 12:41:55] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException...
```

**Comment by hanwoods** [comment]
It seems I'm still experiencing this problem too, but with 3 copies of each log. I can't seem to reporduce the issue locally, but its happening in our production environments.

config.yml
`
monolog:
    channels: ['etl']
    handlers:
        etl:
            level:    info
            type:     stream
            buffer_size: 20
            path:     '%kernel.logs_dir%/etl.log'
            channels: [etl]
`
composer.json
`
"symfony/monolog-bundle": "^3.1.0",
"symfony/polyfill-apcu": "^1.0",
"symfony/swiftmailer-bundle": "^2.3.10",
"symfony/symfony": "3.3.*",
`
etl.log
`
[2018-10-16 13:55:34] etl.INFO: Job id: 8
[2018-10-16 13:55:34] etl.INFO: Job id: 8
[2018-10-16 13:55:34] etl.INFO: Job id: 8
`

**Comment by diditoumoro** [comment]
was this issue being solved? as we are facing the same issue with monolog logging message 3 times
