### ISSUE TITLE
[VarDumper][WebProfilerBundle] Wrong positioning on Dumped result 

### ISSUE THREAD

**Issue by unexge** [symfony/symfony#17127]
![screen shot 2015-12-23 at 20 18 50](https://cloud.githubusercontent.com/assets/16212576/11982435/c4482dcc-a9b3-11e5-9193-ccf18be069e4.png)

User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by sstok** [comment]
This should be already fixed in 2.7-dev https://github.com/symfony/symfony/pull/16825

**Comment by jakzal** [comment]
@unexge can you confirm please?

**Comment by unexge** [comment]
i've Symfony 3.0.0 and issue still continues. 

even if ```z-index: 99999``` applied the dumped element  

![screen shot 2015-12-26 at 09 00 46](https://cloud.githubusercontent.com/assets/16212576/12005518/0d98c8ce-abb2-11e5-9dd6-87f8178cca0e.png)

seems like, this happen because, [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

we need to add ```z-index``` to base ```.sf-toolbar``` class

![screen shot 2015-12-26 at 09 14 53](https://cloud.githubusercontent.com/assets/16212576/12005526/817f7a30-abb2-11e5-8f17-9eca7aab7c7d.png)

**Comment by jakzal** [comment]
@unexge the fix is not present in any released version yet. You'd need to try a dev version or wait for next 2.7 or 3.0 release.

**Comment by unexge** [comment]
@jakzal now i try with fresh install of `3.1.0-dev`, issue still continues for me.

![screen shot 2015-12-26 at 11 49 15](https://cloud.githubusercontent.com/assets/16212576/12005952/2954bbee-abc7-11e5-9d34-1c0d0cc40ef2.png)


in https://github.com/symfony/symfony/issues/17127#issuecomment-167292250, i try to say, i applied changes from https://github.com/symfony/symfony/pull/16825 manually, sorry for my bad english :smile:

**Comment by javiereguiluz** [comment]
Closing it as fixed in the latest Symfony versions. Example:

![dumper_z_index](https://cloud.githubusercontent.com/assets/73419/12888476/9d3e78da-ce7a-11e5-9e16-3a777064a1d5.png)
