### ISSUE TITLE
[Form] Symfony not selecting choice based on default choice data

### ISSUE THREAD

**Issue by MichaelMackus** [symfony/symfony#17939]
# Issue

Symfony v2.8.3 is not selecting the default choice based on data set via the "data" parameter, when the choices consist of value objects. Its also not properly populating the "value" of the choices.

# Steps to reproduce

```bash
git clone https://github.com/MichaelMackus/symfony-sandbox.git -b symfony-bug-default-choice-data
composer install
php app/console server:start
```

Note: this is just a symfony project created with `symfony new acme 2.8`

# Results

When navigating to http://127.0.0.1:8000

![2016-02-26-112115_417x217_scrot](https://cloud.githubusercontent.com/assets/737162/13362973/14c59604-dc7c-11e5-9109-071af5ab4ab8.png)
![2016-02-26-112152_453x161_scrot](https://cloud.githubusercontent.com/assets/737162/13362975/16496aaa-dc7c-11e5-8cb4-dca989606b7b.png)

# Expected Results

"object 1" should be selected, but its not. Also, the values should be the string representation of the value objects (e.g. "object 1", "object 2", etc.), but its a simple numerical index.

Take a look at [MyValueObject](https://github.com/MichaelMackus/symfony-sandbox/blob/symfony-bug-default-choice-data/src/AppBundle/Data/MyValueObject.php) and [MyChoiceType](https://github.com/MichaelMackus/symfony-sandbox/blob/symfony-bug-default-choice-data/src/AppBundle/Form/MyChoiceType.php) in particular. [Composer](https://github.com/MichaelMackus/symfony-sandbox/blob/symfony-bug-default-choice-data/composer.lock#L1855-L1988) is locked to symfony 2.8.3

Form submission works fine, and the resulting object gets returned properly from the form. Its just default data that seems broken.

# Workaround

Workaround is to add this to the choice default options:

```php
       // important if you rely on your option value attribute (e.g. for JavaScript)
       // this will keep the same functionality as before
       'choice_value' => function ($choice) {
           return $choice;
       }, 
```

But annoying, and the docs report this as fixed in 2.8

**Comment by HeahDude** [comment]
Hi @MichaelMackus, there were many `ChoiceType` bugs fixed in the last release of 2.8. Could you please update to the current 2.8.3 and confirm your issue ?

Some pieces of your form type implementation might help if so.

**Comment by MichaelMackus** [comment]
@HeahDude I just updated my repo to 2.8.3, and the problem persists:

![2016-03-03-094717_1272x463_scrot](https://cloud.githubusercontent.com/assets/737162/13503612/2accddba-e125-11e5-88f9-0809751e6bc5.png)

![2016-03-03-094725_468x152_scrot](https://cloud.githubusercontent.com/assets/737162/13503615/2dde2d4c-e125-11e5-99a2-07d3a7b3fa13.png)

**Comment by HeahDude** [comment]
Thanks for the update. Could you please provide a sample of your builder config ? Especially the parts where you define choices, and default data.

**Comment by MichaelMackus** [comment]
All the code is in my repo:

- [Form builder](https://github.com/MichaelMackus/symfony-sandbox/blob/symfony-bug-default-choice-data/src/AppBundle/Controller/DefaultController.php#L20-L24)
- [Form type](https://github.com/MichaelMackus/symfony-sandbox/blob/symfony-bug-default-choice-data/src/AppBundle/Form/MyChoiceType.php)

**Comment by webmozart** [comment]
@MichaelMackus Thanks for reporting this issue! What you experience is not a bug: Symfony compares the choices in the `data` option and the choices you provide in `choices` using strict equality comparison. This is good, because `false !== null`, but `false == null`. However, when dealing with objects, this also means you must pass the same instance.

Second, Symfony will never automatically cast your objects to strings in order to generate the values. That's because Symfony doesn't know whether your object can be cast to a string or not.

The solution is to set the `choice_value` option, as you already figured out. I would also do a string cast in the closure and maybe even add a comment to make your intent explicit:

```php
$resolver->setDefaults([
    'data_class' => MyValueObject::class,
    'choices' => $this->getChoices(),
    'choices_as_values' => true,
    'choice_value' => function (MyValueObject $object) {
        // Use the string representation as values
        return (string) $object;
    },
]);
```

The good thing about `choice_value` is that Symfony will also use this closure to compare two different object instances for equality. Hence even when passing different value objects, they will now be considered "the same" and your first issue is fixed as well. :)

**Comment by miguelrs** [comment]
> The good thing about choice_value is that Symfony will also use this closure to compare two different object instances for equality.

This sentence should definitely be in the docs somewhere (I didn't find it at least) - I spent ages trying to figure this out! 👍
