### ISSUE TITLE
[3.0] AsseticBundle compatibilty

### ISSUE THREAD

**Issue by stephanvierkant** [symfony/symfony#18000]
Symfony/AsseticBundle has still no support for 3.0. A new release was promised months ago, but there is still no update: https://github.com/symfony/assetic-bundle/issues/401. Some people asked if we (as part of the community!) can help, but even that outstretched hand hasn't been answered.

For me, this issue isn't only about the AsseticBundle anymore: not answering questions from the community for months just doesn't feel good to me. I hope this will not become the standard way the Symfony team will communicate with the community.

Please give us an update on this issue.

**Comment by iltar** [comment]
Is the bundle not working with 3.0? [According to the 2.7.1 composer.json it supports 3.0](https://github.com/symfony/assetic-bundle/blob/v2.7.1/composer.json).

**Comment by stof** [comment]
@iltar there is some issues in the released versions to due forgotten deprecations. the master branch should be working

**Comment by Taluu** [comment]
It supports 3.0, but it still doesn't have a tagged release, that;s the whole point. And having to require `dev-master` isn't really reassuring...

**Comment by fabpot** [comment]
I'm closing this issue as AsseticBundle is not managed by the Symfony core team and an issue exists in the bundle repository. I'm very sorry that there is not yet a release compatible with Symfony 3, but there is nothing I can do on y side. @stof said in the related issue that he would make a release, hopefully he will find some time to make it happen soon.
