### ISSUE TITLE
[Form] prototype "required" option is inconsistent with the default option

### ISSUE THREAD

**Issue by sergeyfedotov** [symfony/symfony#18311]
Seems like this issue is related to #15544

```php
class PhotoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Photo::class,
            'required' => false
        ]);
    }
}
```

Actual result:

```html
<input type="text" id="news_photos___name___title" name="news[photos][__name__][title]" required="required" class="form-control" />
```

Prototype is rendered with the "required" option. The explanation of this behavior is given in the comment https://github.com/symfony/symfony/issues/15544#issuecomment-130710735

Is it possible to fix it?

**Comment by HeahDude** [comment]
Hi @sergeyfedotov, thanks for reporting this issue.

It should have been fixed in https://github.com/symfony/symfony/pull/16959 as of 2.3.36, 2.7.8, 2.8.1 and 3.0.1 releases.

Which version are you using ?

**Comment by HeahDude** [comment]
It may be expected if the collection is required any entry will be too.

**Comment by sergeyfedotov** [comment]
@HeahDude I use Symfony 3.0.3 and I saw your PR. As far as I can see your fix only solves the issue with the option specified in the builder:

```php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('photos', CollectionType::class, [
            'entry_type' => PhotoType::class
            'required' => false
        ])
    ;
}
```

But it does not solve the problem with the option specified as default.

**Comment by HeahDude** [comment]
It seems expected to me since `PhotoType` options are overridden by `entry_options` which are by default the same as the `CollectionType` options.

Am I missing something here ?

**Comment by sergeyfedotov** [comment]
Child forms inherit the non-required option from the parent form unlike the prototype. The forms existing in the collection are rendered without the required attribute and prototype is rendered with the required attribute. This seems like inconsistent behavior

**Comment by HeahDude** [comment]
>Child forms inherit the non-required option from the parent form unlike the prototype

This contradicts a tested behavior, see:
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Tests/Extension/Core/Type/CollectionTypeTest.php#L305

It should be expected that `required` default is overridden with the parent's default.

So what looks inconsistent to me is that it actually does not happen for the child forms but only for the prototype (the opposite of your suggestion).

**Comment by sergeyfedotov** [comment]
I wrote two tests to demonstrate the expected behaviour: https://github.com/sergeyfedotov/symfony-form/commit/7b75c4775dd2f0dcaae470328f19958f055ded07

Both tests are now failed with the same assertion:

```
There were 2 failures:

1) Symfony\Component\Form\Tests\Extension\Core\Type\CollectionTypeTest::testPrototypeSetNotRequiredIfParentNotRequired
"prototype" should not be required
Failed asserting that true is false.

/home/sergey/Development/symfony-form/Tests/Extension/Core/Type/CollectionTypeTest.php:334

2) Symfony\Component\Form\Tests\Extension\Core\Type\CollectionTypeTest::testPrototypeSetNotRequiredIfParentNotRequiredAndChildRequired
"prototype" should not be required
Failed asserting that true is false.

/home/sergey/Development/symfony-form/Tests/Extension/Core/Type/CollectionTypeTest.php:353
```

**Comment by HeahDude** [comment]
Ok thanks, I misunderstood your hierarchy.

Would you like to work on a patch ? Otherwise I may look into it.

**Comment by HeahDude** [comment]
See #18317 for a fix.
