### ISSUE TITLE
critical problem with update of symfony/polyfill-php70 and paragonie/random_compat

### ISSUE THREAD

**Issue by IMM0rtalis** [symfony/symfony#18816]
Hi@all,

I updated my symfony with 2.* and got the following error:

> There is no suitable CSPRNG installed on your system
> vendor/paragonie/random_compat/lib/random.php at line 185

So I searched for the error and found this:
[https://github.com/paragonie/random_compat/issues/99](https://github.com/paragonie/random_compat/issues/99)
I am using this Version of php: PHP 5.6.21 (cli) (built: Apr 29 2016 07:55:24)

The solution was to add "paragonie/random_compat": "~1.4", manually to the composer. but this is really a problem. First nothing was working and i had to search for the "bug/feature".

It's because of [symfony/polyfill-php70](https://packagist.org/packages/symfony/polyfill-php70#v1.2.0) which is using [paragonie/random_compat](https://packagist.org/packages/paragonie/random_compat)

Any ideas how to avoid this problem? I mean... I dont want to have other users the same problem and headache...

Best regards,
Florian

**Comment by Tobion** [comment]
The polyfill works with `paragonie/random_compat: ~1.0|~2.0`. At the end it's your decision what version  of random_compat you want to install. I don't see what symfony or polyfill can do about it.

**Comment by javiereguiluz** [comment]
@IMM0rtalis maybe you can lock your maximum PHP version in `composer.json` ? Try this:

```json
{

    "config": {
        "platform": {
            "php": "5.6"
        }
    }
}
```

**Comment by RubenHarms** [comment]
@Tobion: I disagree Symfony depends on polyfill, even if there is no version instruction in your composer file, it will be installed. So pollyfill or symfony made the wrong decision. Although you can change the version by adding a line in your composer it's not very user-friendly.

**Comment by javiereguiluz** [comment]
@RubenHarms I agree.

**Comment by Tobion** [comment]
Should be reported to https://github.com/symfony/polyfill

**Comment by javiereguiluz** [comment]
I'm closing this as fixed by https://github.com/symfony/polyfill/pull/44  If you don't agree. please reopen it. Thanks!

**Comment by Tobion** [comment]
symfony/polyfill#44 introduced this problem and didn't fix it.

**Comment by javiereguiluz** [comment]
Wow! A total misunderstanding on my behalf! I'm sorry. Reopening.

**Comment by nicolas-grekas** [comment]
Still, this should be reported on the polyfill repos.

**Comment by Tersoal** [comment]
Hi all.

I've fixed it in a plesk server adding "/dev/urandom" to open_basedir.

https://tech.enekochan.com/es/2016/06/04/arreglar-no-suitable-csprng-installed-system-en-plesk/
https://forum.owncloud.org/viewtopic.php?t=34286
