### ISSUE TITLE
include(annotations.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#19530]
With current master I always get two "silenced errors" in symfony profiler:

![screenshot 2016-08-04 16 18 50](https://cloud.githubusercontent.com/assets/330436/17405505/07ddea24-5a60-11e6-8931-f3a013d71f3f.png)

I guess it is related to #18533, ping @tgalopin.

**Comment by tgalopin** [comment]
It is, indeed. If you run `bin/console cache:clear`, it should disappear (it's a file created on warm-up).

**Comment by gharlan** [comment]
It does not disappear, and there is no `annotations.php`, only a `annotations.map`.

**Comment by gharlan** [comment]
Yeah, sorry.

**Comment by gharlan** [comment]
The two silenced errors are reproducible by deleting cache without warmup, which is the default behavior in symfony-standard after `composer install/update`.

I think this should not be happen.

**Comment by jakzal** [comment]
@gharlan I can't reproduce your issue. Have you tried it on a fresh installation of Standard Edition?

**Comment by gharlan** [comment]
Yes, it is reproducible for me.

Try this:
* `composer create-project symfony/framework-standard-edition sf-test -s dev`
* `composer update`
* Open `app_dev.php`, open Profiler -> Logs -> Silenced PHP Notices

**Comment by gharlan** [comment]
And then:

* `bin/console cache:clear` -> notices are gone
* `composer update` (or `bin/console cache:clear --no-warmup`) -> notices are back

**Comment by nicolas-grekas** [comment]
These are silenced notices isn't it? You shouldn't care, there are harmless.

**Comment by gharlan** [comment]
The initial problem was, that they were not really silent. I always got the logs symbol in debug toolbar, which confused me. 

But this is fixed by https://github.com/symfony/symfony/commit/eddecbd112c13eadac6533b39287205b90430a21.

Since they are really silent now, it is ok for me.
But still I am wondering, why it is necessary to include a non existing file on every page load (when cache was cleared without warmup).

**Comment by javiereguiluz** [comment]
Closing it as fixed because those errors are now silenced.

(by the way, I tried to reproduce this error but I couldn't)

**Comment by givihuda** [comment]
> These are silenced notices isn't it? You shouldn't care, there are harmless.

"silenced" notices that still show up in logs and are "harmless" that we shouldn't care about are distracting false flags; also, I've seen false flags where sometimes they were an indication of a real problem based on a certain situation... so it seems best for "harmless" "silenced" warnings (it literally states "Warning" for me), that we shouldn't care about, if they're actually useless, to not show in logs. Unless there's some unstated reason the Symfony devs think they should still make it there? I'm not seeing the reason based on your reaction.

Anyway, I'm working on an upgrade from Symfony 3.4 to 4, and going through dev.log deprecation warnings and anything else that looks fishy. This still looks fishy, and I'm not sure of the fix; I'm only running it on Mac at the moment though, and I saw it after running `composer install` (after deleting var/cache and vendor folders) so who knows if it shows on our test or prod servers (Linux) or if/when they ever mean there's an issue.
