### ISSUE TITLE
bug kernel.project_dir inconsistency between cli and web

### ISSUE THREAD

**Issue by tristanbes** [symfony/symfony#22721]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | -
| RFC?             | -
| Symfony version  | 3.3.0-BETA1

Hello,

Following the guidelines for `symfony/symfony-standard`, I put in `config_dev.yml`
```config_dev.yml
framework:
    router:
        resource: "%kernel.project_dir%/app/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
```

When clearing the cache via `cache:clear` it throws an exception because it tries to search for `routing_dev.yml` in wrong location

```
  [Symfony\Component\Config\Exception\FileLocatorFileNotFoundException]              
  The file "/var/cache/symfony/project/de_/config/routing_dev.yml" does not exist.
```

the path is clearly wrong, it should be, for my exemple : `/srv/app`). If I dump the `dump($this->getParameter('kernel.project_dir')` in a Controller, it returns `/srv/app`which is right.

I'm running inside a VM, so I had to change cache & logs directories for performance:

```AppKernel.php
// AppKernel.php
public function getCacheDir()
{
    if (isset($_SERVER['VAGRANT']) && $_SERVER['VAGRANT']) {
        return '/var/cache/symfony/project/'.$this->environment;
    }

    return dirname(__DIR__).'/var/cache/'.$this->getEnvironment();
}

public function getLogDir()
{
    if (isset($_SERVER['VAGRANT']) && $_SERVER['VAGRANT']) {
        return '/var/logs/symfony/project';
    }

    return dirname(__DIR__).'/var/logs';
}
```

**Comment by ro0NL** [comment]
What about `resource: "%kernel.project_dir%/app/config/routing_dev.yml"` ?

Or does your config really live in the project dir?

**Comment by tristanbes** [comment]
Yeh, good catch @ro0NL, unfortunatly it doesn't fix the original issue. I edited my orignal post to avoid confusion since after correction the issue remains the same.

**Comment by ro0NL** [comment]
Yes.. the issue happens if you overwrite the cache dir;

```
public function getCacheDir()
{
    return '/tmp/sf/cache/'.$this->getEnvironment();
}

resource: "%kernel.project_dir%/app/config/routing_dev.yml"

bin/console cache:clear

[Symfony\Component\Config\Exception\FileLocatorFileNotFoundException]       
The file "/tmp/sf/cache/de_/app/config/routing_dev.yml" does not exist.
```

Warmup seems to cause it... i.e. `cache:clear --no-warmup && cache:warmup` seems to work fine :)

Status: reviewed

**Comment by stof** [comment]
yeah, warming up the cache during cache clearing is deprecated precisely because it causes lots of weird edge cases.

@fabpot it looks like the special kernel used by the cache warmup has not been updated to ensure it keeps the `%kernel.project_dir%` of the normal kernel. This looks like a bug needing to be fixed before the 3.3 release though.

**Comment by ro0NL** [comment]
Cant reproduce with #22519 applied on master; perhaps that approach needs to be finished :)

**Comment by nicolas-grekas** [comment]
Should be fixed by https://github.com/symfony/symfony/pull/22872, can someone confirm?

**Comment by maxailloud** [comment]
@nicolas-grekas I still have it on my end. And I haven't overwrite anything default path like cache dir.

With Symfony 3.3.2 and

```
PHP 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-3+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.16.0~linux-x64-non_zts71, https://blackfire.io, by Blackfireio Inc.
```

When excuting the command 
```
bin/console cache:clear --no-warmup --env=prod
bin/console cache:warmup --env=prod
```

I still have the error
`"The file "/var/www/1496768087/my-app/app/app/config/routing.yml" does not exist."`

The path should be `/var/www/1496768087/my-app/app/config/routing.yml`. Twice the `app` part of the path.

It's from a fresh project created via `composer create-project symfony/framework-standard-edition my_project_name`.

**Comment by wcanal** [comment]
i think i found something. @maxailloud: i experienced the same problem after i deployed my project (which skips some files like the `composer.json` etc while coping to the production server.). 

**tltr;** just add this to your `AppKernel.php` and you're good to go:
```php
public function getProjectDir()
{
      return dirname(__DIR__);
}
```
because symfony is searching for a composer.json (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php#L315) and can't find it, the project dir stays in `/app` which leads the `kernel.project_dir` environment var to the wrong path name.

maybe it would be a good idea to add the `getProjectDir()` method to the AppKernel.php by default or at least add some notes to the docs.

**Comment by MatthewBooth** [comment]
I second the above and thanks @wcanal for posting that. Helped me out.

I don't copy the composer files on production servers as Jenkins builds everything ready to be transferred. So this was causing an issue until I popped that method in there.

**Comment by MBurchard** [comment]
I run into this problem today during update from Symfony 3.2 to 3.3.4.  
Locally all works fine. Deployed to production, the routing.yml was not found.  
Then I created a new empty project following the [guide][1].  
Creating the function getProjectDir fixed it.  
This issue is marked as fixed, but with what version will this problem be finally gone?

[1]: http://symfony.com/doc/current/setup.html

**Comment by adeanzan** [comment]
I also hit this problem when deploying to production without a composer.json file. If this issue is closed, is there a better one to request that `getProjectDir()` gets added to `AppKernel.php`?

**Comment by Gerfaut** [comment]
Thanks @adeanzan for pointing this out! Same problem when the composer.json is not deployed! :)

**Comment by pcabreus** [comment]
I've been having this problem for a long time without knowing what it was. Thanks @grammit!!!
