### ISSUE TITLE
[Form][Guesser] ValidatorTypeGuesser does not consider validation_groups option

### ISSUE THREAD

**Issue by kriswallsmith** [symfony/symfony#2387]
The `ValidatorTypeGuesser` does not consider the current form's `validation_groups` option when guessing type. This could be fixed by passing the options array to the guesser methods. The signature of the `FormTypeGuesserInterface` methods would look like this:

    function guessType($class, $property, array $options = array());

The default argument is provided for BC.

**Comment by b-durand** [comment]
Any news about this bug?

**Comment by webmozart** [comment]
I'm closing this issue as duplicate of #7868. If this is fixed, it can only be fixed when the groups are passed explicitly, not via a callback.

**Comment by b-durand** [comment]
@webmozart I don't understand why you closed, it's sound like "won't fixed" :disappointed: The field ignores the validation group defines to the form to determine if the field is required or not. It's not related to type of the field is null or not.

**Comment by webmozart** [comment]
@b-durand No. The ticket should be fixed as part of #7868, since that ticket proposes to generally overhaul the guessers and so makes such an improvement possible.

**Comment by lukepass** [comment]
Sorry for necroposting but this is still an issue in Symfony 3.4, correct?

Thanks!

**Comment by xabbuh** [comment]
@lukepass see #7868
