### ISSUE TITLE
RuntimeException after clearing cache

### ISSUE THREAD

**Issue by gharlan** [symfony/symfony#23977]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.3@dev

I'm using symfony/flex with sf 3.3.6 with symfony/config `^3.3@dev` (because of https://github.com/symfony/symfony/issues/23753)

After clearing cache (without warmup) I get this exception:

![screenshot 2017-08-24 15 03 10](https://user-images.githubusercontent.com/330436/29667779-f7d827ea-88dd-11e7-8496-2f29c164b238.png)

After reloading everything is fine.

**Comment by chalasr** [comment]
Already fixed in #23755, will be part of v3.3.7. Thanks for reporting.

**Comment by gharlan** [comment]
@chalasr #23755 fixed my other issue. This issue is not fixed!

**Comment by chalasr** [comment]
Strange, it looks the same. Can you give the steps to reproduce (including the creation of your flex app and the packages you add into)? Are you sure that `symfony/config` is installed in its 3.3-dev version?

**Comment by chalasr** [comment]
You said "with sf 3.3.6", does that mean you require `symfony/symfony`? That would replace any  `symfony/config` requirement.

**Comment by gharlan** [comment]
> does that mean you require symfony/symfony?

No, I'm using these symfony packages (`composer show`):

![screenshot 2017-08-24 23 59 35](https://user-images.githubusercontent.com/330436/29690735-6eb3c7bc-8928-11e7-9019-367312f11d30.png)

> Can you give the steps to reproduce (including the creation of your flex app and the packages you add into)?

I'm trying to create a reproducer package. After some more tests I found out that the exception only happens in a very special sequence:

1. `make cache-clear` (no warmup!)
2. Don't make a hard reload! Click on a link that triggers an ajax call. In my case it is a [pjax](https://github.com/defunkt/jquery-pjax) call. The call needs some time to build the container, so the pjax timeout is reached.
3. Pjax forces a non-ajax call because of the timeout. This call throws the exception.

Again: I will try to provide a reproducer package.

**Comment by gharlan** [comment]
Now I got the same exception with another stacktrace:

![screenshot 2017-08-25 14 46 47](https://user-images.githubusercontent.com/330436/29714695-82d395f2-89a4-11e7-856f-5d52972ed453.png)

This time a reload didn't help. Also `cache:clear` wasn't possible, had to hard delete the cache dir.

Don't know how to reproduce this one. But I try to create the reproducer package for the other exception stacktrace from above at this weekend.

**Comment by nicolas-grekas** [comment]
@gharlan can you please confirm that #23989 fixes the issue?
