### ISSUE TITLE
@Assert\Valid() doesn't work with groups for more than one level of embeddance (Symfony 3.4)

### ISSUE THREAD

**Issue by kate-kate** [symfony/symfony#24246]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.4.*@dev

## Problem description

I've updated to 3.4 version to try using ```@Assert\Valid()``` with groups and found a bug.
For example I have 3 entities: Contract, System, Part. 

Contract has embedded Systems collection and "contract_valid" group. So it has systems field annotated like that:
```
    /**
     * @var System[]|ArrayCollection
     *
     * @Assert\Valid(groups={"contract_valid"})
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\System", mappedBy="contract", cascade={"persist", "remove"})
     */
    private $systems;
```

System has embedded Parts collection and validation group "system_valid". And It has unique serialNumber
```
/**
 * System
 *
 * @ORM\Table(name="system")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SystemRepository")
 *
 * @UniqueEntity("serialNumber", groups={"system_valid", "contract_valid"})
 */
class System
{
    /**
     * @var string
     *
     * @Assert\NotBlank(groups={"system_valid", "contract_valid"})
     * @ORM\Column(name="serialNumber", type="string", length=255, unique=true)
     */
    private $serialNumber;

    /**
     * @var Part[]|ArrayCollection
     *
     * @Assert\Valid(groups={"system_valid", "contract_valid"})
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Part", mappedBy="system", cascade={"persist", "remove"})
     */
    private $parts;
```

And Part itself has no embedded entities, but it also has unique field serialNumber, which is validated for "contract_valid", "system_valid" and its own "part_valid" validation groups
```
/**
 * Part
 *
 * @ORM\Table(name="part")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PartRepository")
 *
 * @UniqueEntity("serialNumber", groups={"part_valid", "system_valid", "contract_valid"})
 */
class Part
{
   
    /**
     * @var string
     *
     * @Assert\NotBlank(groups={"part_valid", "system_valid", "contract_valid"})
     * @ORM\Column(name="serialNumber", type="string", length=255, unique=true)
     */
    private $serialNumber;
```

The problem is the following: when I try to save System with not unique Part serialNumber - validation error will be thrown successfully. But if I try to create Contract with not unique System serialNumber, I see PDO Exception instead of validation error:
<img width="1063" alt="2017-09-18 15 24 51" src="https://user-images.githubusercontent.com/4061805/30541851-adc49560-9c85-11e7-81e2-9afc53238ece.png">

Works the same way when I try to create (or update) Contract with valid System and not unique Part serialNumber:
<img width="1045" alt="2017-09-18 15 35 03" src="https://user-images.githubusercontent.com/4061805/30542236-381c0a94-9c87-11e7-8587-234aff5fda8e.png">

Also, when I remove "contract_valid" group from Part annotations and from System parts ```@Assert\Valid()```, it also works well for System (and obviously doesn't works for Part at all).

I can create repository with represented bug, if helps.

**Comment by xabbuh** [comment]
Having a small example project allowing to reproduce your issue would indeed be very helpful (I guess you won't need to set up any persistence layer as the issue should be reproducible using other constraints too, right?).

**Comment by kate-kate** [comment]
Hello, I've created the [project](https://github.com/kate-kate/valid_embed) 
There are three simple entity classes without persistence layer and I used ```NotBlank``` and ```Length``` constraints to reproduce issue.
In ```/part``` and ```/system``` routes validation works well. Problem is seen at ```/contract```

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
Status: Reviewed

**Comment by xabbuh** [comment]
@kate-kate Thanks for the great reproducer. I was able to identify the issue. Can you confirm that #24983 does fix it for you?

**Comment by KamilPesek** [comment]
I think I have same problem as @kate-kate. I have constraint defined like 
```
/**
     * @ORM\ManyToOne(targetEntity="Address", cascade={"persist"})
     * @Assert\Valid(
     *     groups={"extendedPersonMailingAddressNotSame"}
     * )
     */
    private $mailingAddress = null;
```

and then, I have group sequence validator
```

    /**
     *
     * Set conditional validation groups
     *
     * @return array
     */
    public function getGroupSequence()
    {

        if (!$this->mailingAddressSameAsPermanent) {
            $groups[] = 'extendedPersonMailingAddressNotSame';
        }

        return [$groups];  //this returns   ['extendedPersonMailingAddressNotSame']
    }

```

If I remove 'groups={"extendedPersonMailingAddressNotSame"}', everything works. 
It also works when used with NotBlank
```
@Assert\NotBlank(
  groups={"extendedPersonMailingAddressNotSame"}
)
```

Unfortunatelly [#24983](https://github.com/symfony/symfony/pull/24983) doesn't work for me.

**Comment by xabbuh** [comment]
@KamilPesek I pushed another update to the PR. Can you check that too?

**Comment by KamilPesek** [comment]
Unfortunately no change for me. It still doesn't work in 3.4.3. 
And I am pretty sure that I have everything right, because:
1) when i remove groups from 
```
@Assert\Valid(
     groups={"extendedPersonMailingAddressNotSame"}
  )
```
 it works
2) it also works with any other validation constraint, eg. NotBlank

Any suggestions?

**Comment by xabbuh** [comment]
@KamilPesek Please open a new issue and best also provide an example application that allows to reproduce your issue.

**Comment by KamilPesek** [comment]
@xabbuh oppened here #25726
