### ISSUE TITLE
Cache: RedisAdapter connects during cache:warmup (at least for Doctrine)

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#24865]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Symfony version  | 3.2?

Steps to repeat:

1) `git clone git@github.com:weaverryan/flex-redis-bug.git`

2) `composer install`

It will explode with:

<img width="1272" alt="screen shot 2017-11-07 at 3 15 49 pm" src="https://user-images.githubusercontent.com/121003/32515567-922c23d4-c3ce-11e7-865c-b8920921b2bc.png">

The project is a standard Flex app, but with the following changes:

A) Doctrine ORM is installed

B) The `app` cache uses redis (see `framework.yaml`)

C) We're in the `prod` environment

The error happens on `cache:clear`. This comes from the result cache configured by default in `prod` for Doctrine: https://github.com/symfony/recipes/blob/93d80647f510e00a52db869251136593a2dc2182/doctrine/doctrine-bundle/1.6/config/packages/prod/doctrine.yaml#L28

This is caused by a lack of laziness... *somewhere*. It could be in Doctrine - this whole thing starts when we try to warmup the proxies... which instantiates the entity managers (which instantiates result caches and also connection objects). Or, it could be in the Cache component, where (at least with Redis) a connection to the Redis server is established in order to create the `RedisAdapter` object (even if you never make any connections to it).

Thanks!

**Comment by fabpot** [comment]
This one is important to fix. /cc @nicolas-grekas

**Comment by weaverryan** [comment]
Tangentially related to this: thanks to the same lack of laziness in Doctrine, the Doctrine `Connection` object is also instantiated. This means that a `DATABASE_URL` environment variable *must* be available at `cache:warmup` time. It doesn't need to be *valid* (no connection is make), but it *does* need to be defined:

<img width="1280" alt="screen shot 2017-11-07 at 3 35 32 pm" src="https://user-images.githubusercontent.com/121003/32516437-56ceb114-c3d1-11e7-8249-597c514117c1.png">

**Comment by fabpot** [comment]
@weaverryan This one is more tricky as Doctrine needs the version. So, passing a fake DATABASE_URL is kind of required to pass the DB version so that Doctrine does not attempt to connect to the database for real to get the version. If we can fix that as well, that would be FANTASTIC.

**Comment by bitgandtter** [comment]
Im facing the same issue as @weaverryan, im building a micro-service using flex and 3.3 for now till 4.0 is released to be build and deployed as docker container, i did a workaround setting fake env vars just to get composer install pass, but that is not ideal it should not depend on that variable and allow the docker image to be more clear and final allowing us to deploy the container with the correct env vars

**Comment by aequasi** [comment]
Yeah, these two came up while i've been trying to dockerize a sf4 install. Thanks @weaverryan for making the issue for me :D

**Comment by nicolas-grekas** [comment]
This was left as an exercise to the user :)
Here is the solution:
- `composer req proxy-manager-bridge`
+ apply
```diff
--- a/config/services.yaml
+++ b/config/services.yaml
@@ -26,3 +26,9 @@ services:
     App\Controller\:
         resource: '../src/Controller'
         tags: ['controller.service_arguments']
+
+    cache.default_redis_provider:
+        class: Redis
+        factory: [Symfony\Component\Cache\Adapter\RedisAdapter, createConnection]
+        arguments: ['%env(REDIS_URL)%']
+        lazy: true
```

But I guess we can make RedisAdapter accept a DSN, then create the connection lazily... I'm on it.

**Comment by bitgandtter** [comment]
It would be great to have a similar solution for doctrine @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Doctrine already has a lazy-loading mechanism bundled, can't do much more here.

**Comment by bitgandtter** [comment]
But doctrine is requiring the environment variables to be defined at cache warmup time as @weaverryan mention in previous comment, that makes it obscure at docker build time so we need to define a fake environment variable just to complain with the cache warmup.

**Comment by nicolas-grekas** [comment]
@fabpot @weaverryan can the server version be provided to doctrine using a regular parameter instead? That's the only solution I can think of for this issue.

**Comment by weaverryan** [comment]
Actually, I think the server version problem is a misconception. I believe that (at least *mostly*, if not entirely), the issue of Doctrine trying to establish a database connection during cache warmup has been fixed (in a few places, things have been fixed to be more lazy).

The problem here is `ProxyCacheWarmer`. If I return immediately, then I cache warmup the cache *without* specifying a `DATABASE_URL`. The dependency chain is:

A) `ProxyCacheWarmer` instantiates all the EntityManagers (https://github.com/symfony/symfony/blob/61b753443d6903d8a9644f62caf020fdfca3ef6f/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php#L49)

B) The `EntityManager` requires the `Connection`

C) The instantiation of the `Connection` triggers the error (from the built container) that the `DATABASE_URL` environment variable is not present.

I'm not sure how to *break* that dependency chain. The `Connection` should not be needed in order to get the metadata/proxy information. But that's buried in Doctrine. At the same time, creating a `Connection` object is not really a problem...since no queries are actually made. But since the container checks for the existence of the environment parameter, we hit the issue.

Ideas include:

1) Adding something to make environment variables optional? Kinda doesn't really address the problem (the Connection being instantiated).

2) Create duplicated, "fake" entity manager services, where the `Connection` is some dummy, not-real connection object. Then inject these "fake" entity manager services into `ProxyCacheWarmer` and use *them* to get the metadata needed.  This seems a little nuts, but would indeed work...

**Comment by bitgandtter** [comment]
On my case i use DoctrineMongoDBBundle and have no cache configuration that implies directly a doctrine connection and still get the exception from doctrine requiring the environment variable to be defined

**Comment by nicolas-grekas** [comment]
This is not solvable without setting a default value. The same issue will happen with the redis proxy cache btw.
The only solution to now have this is a lazy proxy from proxy-manager.
Which means there is no solution by default.

**Comment by nicolas-grekas** [comment]
See #24887 for adding laziness to the redis cache.
But as stated, the env var *will have to be defined* at build time, even if a dummy value is used.
The only way around is using a real lazy proxy from proxy-manager, which is able to call a factory lazily.

**Comment by jderusse** [comment]
The same issue affects the Lock component when a cache warmer has a dependency on a LockInterface (configured with redis in the backoffice)

reproduct case on top of @weaverryan 's sample project
```diff
diff --git a/composer.json b/composer.json
index 87e9ddb..0cad6fc 100644
--- a/composer.json
+++ b/composer.json
@@ -9,6 +9,7 @@
         "symfony/console": "^4.0",
         "symfony/flex": "^1.0",
         "symfony/framework-bundle": "^4.0",
+        "symfony/lock": "^4.0@beta",
         "symfony/lts": "^4@dev",
         "symfony/yaml": "^4.0"
     },
diff --git a/config/packages/framework.yaml b/config/packages/framework.yaml
index 919fbbb..e312a1f 100644
--- a/config/packages/framework.yaml
+++ b/config/packages/framework.yaml
@@ -12,6 +12,7 @@ framework:
     #fragments: ~
     php_errors:
         log: true
+    lock: "%env(REDIS_DSN)%"
     cache:
         app: cache.adapter.redis
         default_redis_provider: "%env(REDIS_DSN)%"
\ No newline at end of file
diff --git a/src/CacheWarmer/Foo.php b/src/CacheWarmer/Foo.php
new file mode 100644
index 0000000..f428a8d
--- /dev/null
+++ b/src/CacheWarmer/Foo.php
@@ -0,0 +1,22 @@
+<?php
+
+namespace App\CacheWarmer;
+
+use Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface;
+use Symfony\Component\Lock\LockInterface;
+
+class Foo implements CacheWarmerInterface
+{
+    public function __construct(LockInterface $lock)
+    {
+    }
+
+    public function warmUp($cacheDir)
+    {
+    }
+
+    public function isOptional()
+    {
+        return false;
+    }
+}
```

**Comment by aequasi** [comment]
Does that commit fix the DATABASE_URL issue too, or would you like another issue for that?

**Comment by weaverryan** [comment]
Could you create a separate issue so we can track that Aaron?

**Comment by nicolas-grekas** [comment]
@aequasi it doesn't: 

> The only way around is using a real lazy proxy from proxy-manager, which has tighter integration with the DI component and is able to call a factory lazily.

**Comment by tecnocat** [comment]
May be this help:

https://github.com/symfony/symfony/issues/25157#issuecomment-467811636

**Comment by Warxcell** [comment]
Same issue here. Redis is used for Query/Result and Second Level Cache and it's initialized during `cache:clear` which in our case happens during docker build and breaks the build stage.

**Comment by sokil** [comment]
Same issue. I think we need to go to Doctrine's team, as i see separation of configuration and metadata from entity manager is the only solution to build DI during Docker build and as a result get immutable docker image :(

**Comment by WebDaMa** [comment]
Still having this issue with the symfony/docker building stage:

Had to remove the cache build to prevent it connecting to Redis from Doctrine.
Running the cache:clear on deploy, not ideal.

Also fails when installing assets

**Comment by WebDaMa** [comment]
> Same issue. I think we need to go to Doctrine's team, as i see separation of configuration and metadata from entity manager is the only solution to build DI during Docker build and as a result get immutable docker image :(

Did you found a proper workaround or created a ticket for this with Doctrine?

**Comment by JoniJnm** [comment]
Is there a way to just create the symfony caché container without calling external services like redis?

I'm using in my Dockerfile:
```
bin/console cache:warmup --no-optional-warmers --env=prod
```

But [CachePoolClearerCacheWarmer](https://github.com/symfony/symfony/blob/7.2/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/CachePoolClearerCacheWarmer.php#L51) is not optional, so if the cache.pool uses redis, it breaks.

One way could be use a ENV parameter to "mock" the redis adapter, but the container cache will be wrong for prod
