### ISSUE TITLE
shared: false - does not pass a new instance

### ISSUE THREAD

**Issue by rhift** [symfony/symfony#25263]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | > 3.2

```yml
# di-bug.yml

services:
  dependent_collection:
    class: DependantCollection
    calls:
      - [addDependant, ['@dependent_1']]
      - [addDependant, ['@dependent_2']]
  dependent_1:
    class: Dependent
    calls:
      - [setName, ['dependent_1']]
      - [setDependency, ['@dependency']]
    shared: false
  dependent_2:
    class: Dependent
    calls:
      - [setName, ['dependent_2']]
      - [setDependency, ['@dependency']]
    shared: false
  dependency:
    class: Dependency
    shared: false
```
```php
<?php
// di-bug.php

declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\YamlFileLoader;

class DependantCollection
{
    protected $_dependents = [];

    public function addDependant(Dependent $dependent): DependantCollection
    {
        if (isset($this->_dependents[$dependent->getName()])) {
            throw new \LogicException('Dependent with name ' . $dependent->getName() . 'is already set.');
        }
        $this->_dependents[$dependent->getName()] = $dependent;

        return $this;
    }
}

class Dependent
{
    protected $_dependency;
    protected $_name;

    public function setDependency(Dependency $dependency): Dependent
    {
        if ($this->_dependency === null) {
            $dependency->setDependent($this);
            $this->_dependency = $dependency;
        }else {
            throw new \LogicException('Dependency is already set.');
        }

        return $this;
    }

    public function setName(string $name): Dependent
    {
        if ($this->_name === null) {
            $this->_name = $name;
        }else {
            throw new \LogicException('Name is already set.');
        }

        return $this;
    }

    public function getName(): string
    {
        if ($this->_name === null) {
            throw new \LogicException('Name is not set.');
        }

        return $this->_name;
    }
}

class Dependency
{
    protected $_dependent;

    public function setDependent(Dependent $dependent): Dependency
    {
        if ($this->_dependent === null) {
            $this->_dependent = $dependent;
        }else {
            throw new \LogicException('Dependent is already set.');
        }

        return $this;
    }
}

$containerBuilder = new ContainerBuilder();
$loader = new YamlFileLoader($containerBuilder, new FileLocator(__DIR__));
$loader->load('./di-bug.yml');

$dependentCollection = $containerBuilder->get('dependent_collection');

return;
```

Notice that the first pass injects a `Dependency` into the first `Dependent`, however the reference to `Dependency` is maintained and the same `Dependency` is injected into the second `Dependent` resulting in a `LogicException` with the message `Dependent is already set.` since it is the same `Dependency` object as was passed to the first `Dependent`.

This works correctly in 3.2.

**Comment by nicolas-grekas** [comment]
This works in 3.3, but fails in 3.4.
It also fails in 3.2 to 3.4 when the container is compiled + dumper (related to inlinining pass),
which is the most common way to use the container in full-Symfony apps.
This means the expected behavior is not obvious, both on the "why" side, and on the "expected" one.

**Comment by nicolas-grekas** [comment]
Fixed in #25312

**Comment by rhift** [comment]
Hi @nicolas-grekas - ty for taking a look at this and so fast! 

The newly added `testProcessDoesInlineNonSharedService` test does pass in `3.4.x-dev`. However, the example provided here still fails with or without compilation of the container.  Perhaps I am doing something wrong or misunderstanding in some way.

**Comment by nicolas-grekas** [comment]
I'll double check tomorrow...

**Comment by nicolas-grekas** [comment]
Just tested again, works for me on 3.3 and 3.4 now, dumped/compiled or not.

**Comment by nicolas-grekas** [comment]
You're not using https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/PassConfig.php? How strange is that :)
So yes, inlining requires repeated pass, otherwise only part of the processing is done.
