### ISSUE TITLE
Compile error after cache clear and warmup

### ISSUE THREAD

**Issue by coudenysj** [symfony/symfony#25654]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | -
| RFC?             | no
| Symfony version  | 3.4.2

This is related to #24885.

```
Fatal Compile Error: require(): Failed opening required '/.../cache/prod/Container3no4t0t/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/share/php')
```

I run a couple commands during deployment, clear cache, warm cache, other commands, and always get a Fatal Compile Error after the cache warmup:

```
php bin/console cache:clear --no-warmup --env=prod
php bin/console cache:warmup --env=prod
php bin/console rabbitmq-supervisor:rebuild -vv --no-interaction --env=prod
```

**Comment by nicolas-grekas** [comment]
Would you be able to try with 3.4@dev? I think this is fixed already.
Otherwise, can you provide a reproducer?

**Comment by coudenysj** [comment]
So the problem probably lies in the fact that the supervisor processes still look at the old container folder (in memory problem).

**Comment by fancyweb** [comment]
So I had the same error showing up when deploying on prod since I updated to 3.4. I took the time to investigate this problem and found how to reproduce it.

Use this command on a fresh Symfony standard edition : 

```php
<?php

namespace AppBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Process\Process;

class TempCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('app:temp');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     *
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $process = new Process('php bin/console cache:clear');
        $process->run();

        return 0;
    }
}
```

Works fine on 3.3, fails on 3.4.

![untitled](https://user-images.githubusercontent.com/3658119/34518312-2acda07c-f07f-11e7-898d-dde8e8da70f4.png)

Also I can confirm you that using the same fix as in https://github.com/symfony/symfony/pull/24908 is working here. If you have `$this->getApplication()->setDispatcher(new EventDispatcher());` at the beginning of the command, there is no error.

**Comment by fancyweb** [comment]
@nicolas-grekas You were right, I just tested it on 3.4@dev and the error is gone.

@coudenysj IMHO, this issue can be closed.

**Comment by coudenysj** [comment]
I'll have a look at 3.4@dev.

Currently having the issue in v3.4.2 (29961b693fa2).

**Comment by coudenysj** [comment]
I upgraded (https://github.com/symfony/symfony/compare/29961b693fa2157a3f349d1a801f9f8742be4e03...1b36d0324681090ff1ca0d1d397b9f45c67612ed), but still have the issue. It is probably due to the fact that processes still look at the old container.

I'll look in to it later and reopen this issue if it is a problem in Symfony.

**Comment by AntoineLemaire** [comment]
I had the same error, I upgraded to v3.4.3 in prod and problem seams to be fixed

**Comment by fancyweb** [comment]
I still have the problem too after upgrading to 3.4.3. My reproducer works but not my real code.

**Comment by AntoineLemaire** [comment]
Same problem here, I can observe the problem in production, we have many logs with Sentry. But I didn't managed to reproduce it yet, Sentry is not very helpful and I don't know what throw the error

**Comment by nicolas-grekas** [comment]
@fancyweb @AntoineLemaire could you please confirm that your case is fixed by #25733?

**Comment by nicolas-grekas** [comment]
@coudenysj also :)

**Comment by fancyweb** [comment]
It doesn't fix it for me but I guess the problem could also be in the way I deploy or in my setup.
I use a shell script with the following content : 
```sh
sudo ./stop_sv_services.sh
cd /path/to/my/site/dir
git pull origin prod
composer install --no-dev --optimize-autoloader
php bin/console doctrine:migrations:migrate -n
php bin/console assetic:dump
php bin/console doctrine:cache:clear-metadata
php bin/console doctrine:cache:clear-result
php bin/console doctrine:cache:clear-query
php bin/console cache:clear
php bin/console cache:warmup
sudo ./start_sv_services.sh
```
I use runsv to run commands continually. The `stop_sv_services` and `start_sv_services` scripts are used to restart them when I deploy. I changed it recently to try to fix this problem but back in 3.3 I had only one script that restarted them at the end and it was working.
This shell script is started from a Symfony command with a `Process` as in my previous message. If I run this command I get the error. However if I directly run the script there is no error. Also ofc if I comment the `cache:clear` there is also no error.

**Comment by coudenysj** [comment]
This is exactly where the problem lies. If you have long running processes, you will hit this error.

The processes have a path to the old container in memory, which doesn't exist anymore after a cache rebuild.

I try to solve it by stopping the long running processes (Symfony commands) before I rebuild the cache, and start them again afterwards.

This still sometimes gives me an error when someone clears the cache directly via the commands, so this change is kind of annoying.

**Comment by nicolas-grekas** [comment]
There is no fix to this on Symfony's side: if the underlying code changes, you must restart your long running processes, no way around.

**Comment by nicolas-grekas** [comment]
(it could happen with any class really)
The good news is that the name of the cache folder should be immutable for the same configuration now, so that clearing the cache while not actually changing anything should not break your long running processes.
If the name is not stable, look at non-core bundles.

**Comment by fancyweb** [comment]
The processes are restarted (stopped before cache:clear and then started again). Also why the error doesn't appear when the script is directly executed ?

**Comment by coudenysj** [comment]
Just as a clarification for users having the same issue:

The problem lies in the fact that Symfony changes the class name of the generated container (and thus changes the filename).

When you have long running scripts, they have the old container file open (in memory), but it does not exist anymore. You could check this with `lsof -p PID`.

The process keeps running, until you ask it to do something, and then it crashes (because the file is gone).

In the older versions of Symfony, the file was just loaded again (because the filename was the same) and everything worked fine.

Something to keep in mind.

**Comment by nicolas-grekas** [comment]
> In the older versions of Symfony, the file was just loaded again

Actually, it was not loaded again: the old file was still loaded and used for the whole life of the process.
Thus, it contained potentially obsolete service factories, potentially leading to other kind of bugs on for these processes (less visible ones.)

**Comment by nicolas-grekas** [comment]
@fancyweb btw you snippet is strange: `cache:clear` should have `--no-warmup` if you warmup just after (but note that it's also fine since 3.3/3.4 to just `cache:clear` and let it are about warmups.
The second thing that is strange is running migrations before clearing the cache.
