### ISSUE TITLE
[Security] SimpleAuthenticationProvider is broken

### ISSUE THREAD

**Issue by leofeyer** [symfony/symfony#26775]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Symfony version  | 3.4.7

The changes from #26370 break the simple authentication provider.

https://github.com/symfony/symfony/blob/341682e079a2f00765d1768d0ecc3016b8c66dd3/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php#L47-L48

`$authToken->getUser()` returns a "UserInterface instance, an object implementing a __toString method, or the username as a regular string", however the `UserChecker::checkPreAuth()` method allows a UserInterface instance only. An anonymous token results in the following exception:

```
Type error: Argument 1 passed to Symfony\Component\Security\Core\User\UserChecker::checkPreAuth() must be an instance of Symfony\Component\Security\Core\User\UserInterface, string given, called in …/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php on line 49
```

@i3or1s /cc

**Comment by iltar** [comment]
A few questions:
 - Is this a refresh or a new authentication attempt?
 - Is the firewall stateless?
 - Can you provide a reproducer?

**Comment by leofeyer** [comment]
I don't think it is necessary to set up a test case. Just compare the phpDocs of the two interfaces:

**TokenInterface::getUser()**

```php
    /**
     * Returns a user representation.
     *
     * @return mixed Can be a UserInterface instance, an object implementing a __toString method,
     *               or the username as a regular string
     *
     * @see AbstractToken::setUser()
     */
    public function getUser();
```

**UserCheckerInterface::checkPreAuth()** 

```php
    /**
     * Checks the user account before authentication.
     *
     * @throws AccountStatusException
     */
    public function checkPreAuth(UserInterface $user);
```

You cannot pass the `getUser()` return value to the `checkPreAuth()` method without further validation.

**Comment by i3or1s** [comment]
Would it make sense to run `checkPreAuth` and `checkPostAuth` only in case `$authToken->getUser()` is instance of `UserInterface`

**Comment by chalasr** [comment]
I propose to load the user in this case, see #26788.

**Comment by aureliengiry** [comment]
Hi, I have same issue.
No issue on symfony 3.4.6 but on 3.4.7.
And I have same issue on symfony 2.8.37, but it's ok on 2.8.32

**Comment by chalasr** [comment]
Hey, the patch has been merged but not released yet, it will be fixed in 3.4.8

**Comment by xabbuh** [comment]
3.4.8 has been released

**Comment by aschempp** [comment]
Unfortunately, the new implementation is broken as well, see my comment in https://github.com/symfony/symfony/pull/26788#issuecomment-380586927

**Comment by crmpicco** [comment]
Was this issue fixed in 3.4 only? Has it been backported to 2.8?

**Comment by BonBonSlick** [comment]
Dunno why started to receive this issue.
  ```
  "symfony/security-acl": "^v3.0.4",
    "symfony/security-bundle": "^v5.2.10",
    "symfony/security-core": "^v5.2.10",
    "symfony/security-guard": "^v5.2.10",
    "symfony/security-http": "^v5.2.10",
```

So the issue persists somewhere
```

TypeError {#1794
  #message: "Return value of Symfony\Component\Security\Core\Authentication\Token\AbstractToken::getUserIdentifier() must be of the type string, null returned"
  #code: 0
  #file: "/var/www/hint_api/vendor/symfony/security-core/Authentication/Token/AbstractToken.php"
  #line: 79
  trace: {
    /var/www/hint_api/vendor/symfony/security-core/Authentication/Token/AbstractToken.php:79 {
      Symfony\Component\Security\Core\Authentication\Token\AbstractToken->getUserIdentifier(): string …
      ›     // @deprecated since 5.3, change to $user->getUserIdentifier() in 6.0
      ›     return method_exists($this->user, 'getUserIdentifier') ? $this->user->getUserIdentifier() : $this->user->getUsername();
      › }
    }
    /var/www/hint_api/vendor/symfony/security-core/Authentication/Token/AbstractToken.php:259 {
      Symfony\Component\Security\Core\Authentication\Token\AbstractToken->__toString() …
      › 
      ›     return sprintf('%s(user="%s", authenticated=%s, roles="%s")', $class, $this->getUserIdentifier(), json_encode($this->authenticated), implode(', ', $roles));
      › }
    }
    /var/www/hint_api/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php:179 {
      Monolog\Formatter\NormalizerFormatter->normalize($data, int $depth = 0) …
      ›     /** @var string $value */
      ›     $value = $data->__toString();
      › } else {
    }
    /var/www/hint_api/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php:159 {
```

**Comment by BonBonSlick** [comment]
This is because some package was updated with security package where was added new method

```
    /**
     * @deprecated
     */
    public function getUsername(): void { }

    public function getUserIdentifier(): string {
        return $this->secret()->value();
    }
```

**Comment by xabbuh** [comment]
@BonBonSlick Does it mean your issue has been solved?
