### ISSUE TITLE
The process has been signaled with signal "11".

### ISSUE THREAD

**Issue by gmoqa** [symfony/symfony#29341]
**Symfony version(s) affected**: 4.1.8

**Description**  
```(in built in server)[ERROR] The process has been signaled with signal "11".```

**How to reproduce**  
In any new project, if you clone ```symfony/website-skeleton``` run built-in server

**Additional context**  
I think it has a relationship with latest [Routing] fixes ```@Route```

**Comment by askuri** [comment]
Temporary fix: create a project using an older version of the skeleton:
`composer create-project symfony/website-skeleton=4.1.7.10 my_project`
And update it after:
`composer update`

**Comment by arendjantetteroo** [comment]
Also got hit by this, anything i can do to help figure out where the issue is originating? 

4.1.7 works fine, 4.1.8 breaks. 

I got this issue on my ci with php version 7.2.12-1 running the webserver bundle. 
Get:192 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.2-cli amd64 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 [1407 kB]

Locally i run on 7.2.11-3 and i dont' have this issue. 

Comments on https://symfony.com/blog/symfony-4-1-8-released seem to indicate the php version is related to this issue. 

@nicolas-grekas

**Comment by nicolas-grekas** [comment]
@arendjantetteroo thanks for the update, it's going to be fun to debug. That's a PHP bug apparently. Dunno what we do in 4.1.8 to hit it...

**Comment by atfera** [comment]
Same for me.
A **temporary fix** I found is to update to php 7.3. For macOS users, I first uninstalled the php package I installed with homebrew then followed the instructions here: https://php-osx.liip.ch/

**Comment by arkwlcz** [comment]
Same for me too.
After updating Symfony to 4.1.8 the nginx 502 (Gateway timeout) error appear.

Maybe my investigation will be helpful: After deleting file: var/cache/dev/srcDevDebugProjectCointainerUrlMatcher.php.meta the application started correctly once, and then crashed again until I deleted the file again. Setting the .env option APP_DEBUG=0 solved problem and the application runs OK, but when I turn to APP_DEBUG=1 it crashes with NGINX error 502.

Downgrading to Symfony 4.1.7 solved problem totally.

**Comment by nicolas-grekas** [comment]
Could it be #29107? can anyone try to revert that patch locally and see how it goes?

**Comment by nicolas-grekas** [comment]
Alternatively, could anyone also check if #29349 fixes the issue?

**Comment by parasetam0l** [comment]
> Could it be #29107? can anyone try to revert that patch locally and see how it goes?
Not fixed but

> Alternatively, could anyone also check if #29349 fixes the issue?
Fixed my problem. Thank you @nicolas-grekas .

**Comment by nicolas-grekas** [comment]
Fixed in #29349. Thanks for the help.

**Comment by Rmy5** [comment]
Still having this issue, even after updating symfony to latest.
Getting "Bad gateway" on nginx server.

**Comment by xabbuh** [comment]
@Rmy5 What's the output of `composer show`?

**Comment by Rmy5** [comment]
@xabbuh 
composer show ouput is: 
doctrine/annotations                v1.6.0  Docblock Annotations Parser
doctrine/cache                      v1.8.0  Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.5.0  Collections Abstraction library
doctrine/common                     v2.10.0 PHP Doctrine Common project is a library that provides additional functionality that other Doctrine ...
doctrine/data-fixtures              v1.3.1  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.8.0  Database Abstraction Layer
doctrine/doctrine-bundle            1.10.0  Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5   Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   3.0.4   Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v1.3.1  Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0  Doctrine Event Manager component
doctrine/inflector                  v1.3.0  Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.1.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.8.1  Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.6.3  Object-Relational-Mapper for PHP
doctrine/persistence                v1.1.0  The Doctrine Persistence project is a set of shared interfaces and functionality that the different ...
doctrine/reflection                 v1.0.0  Doctrine Reflection component
easycorp/easy-log-handler           v1.0.7  A handler for Monolog that optimizes log messages to be processed by humans instead of software. Imp...
egulias/email-validator             2.1.6   A library for validating emails against several RFCs
facebook/webdriver                  1.6.0   A PHP client for Selenium WebDriver
fig/link-util                       1.0.0   Common utility implementations for HTTP links
jdorn/sql-formatter                 v1.2.17 a PHP SQL highlighting library
monolog/monolog                     1.24.0  Sends your logs to files, sockets, inboxes, databases and various web services
nikic/php-parser                    v4.1.0  A PHP parser written in PHP
ocramius/package-versions           1.3.0   Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager              2.2.2   A library providing utilities to generate, instantiate and generally operate with Object Proxies
phpdocumentor/reflection-common     1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrie...
phpdocumentor/type-resolver         0.4.0   
psr/cache                           1.0.1   Common interface for caching libraries
psr/container                       1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/link                            1.0.0   Common interfaces for HTTP links
psr/log                             1.1.0   Common interface for logging libraries
psr/simple-cache                    1.0.1   Common interfaces for simple caching
sensio/framework-extra-bundle       v5.2.2  This bundle provides a way to configure your controllers with annotations
swiftmailer/swiftmailer             v6.1.3  Swiftmailer, free feature-rich PHP mailer
symfony/asset                       v4.1.8  Symfony Asset Component
symfony/browser-kit                 v4.1.8  Symfony BrowserKit Component
symfony/cache                       v4.1.8  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                      v4.1.8  Symfony Config Component
symfony/console                     v4.1.8  Symfony Console Component
symfony/css-selector                v4.1.8  Symfony CssSelector Component
symfony/debug                       v4.1.8  Symfony Debug Component
symfony/debug-bundle                v4.1.8  Symfony DebugBundle
symfony/debug-pack                  v1.0.6  A debug pack for Symfony projects
symfony/dependency-injection        v4.1.8  Symfony DependencyInjection Component
symfony/doctrine-bridge             v4.1.8  Symfony Doctrine Bridge
symfony/dom-crawler                 v4.1.8  Symfony DomCrawler Component
symfony/dotenv                      v4.1.8  Registers environment variables from a .env file
symfony/event-dispatcher            v4.1.8  Symfony EventDispatcher Component
symfony/expression-language         v4.1.8  Symfony ExpressionLanguage Component
symfony/filesystem                  v4.1.8  Symfony Filesystem Component
symfony/finder                      v4.1.8  Symfony Finder Component
symfony/flex                        v1.1.8  Composer plugin for Symfony
symfony/form                        v4.1.8  Symfony Form Component
symfony/framework-bundle            v4.1.8  Symfony FrameworkBundle
symfony/http-foundation             v4.1.8  Symfony HttpFoundation Component
symfony/http-kernel                 v4.1.8  Symfony HttpKernel Component
symfony/inflector                   v4.1.8  Symfony Inflector Component
symfony/intl                        v4.1.8  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle                v1.9.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can ...
symfony/monolog-bridge              v4.1.8  Symfony Monolog Bridge
symfony/monolog-bundle              v3.3.1  Symfony MonologBundle
symfony/options-resolver            v4.1.8  Symfony OptionsResolver Component
symfony/orm-pack                    v1.0.5  A pack for the Doctrine ORM
symfony/panther                     v0.2.0  A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge              v4.2.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu           v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring           v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72              v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process                     v4.1.8  Symfony Process Component
symfony/profiler-pack               v1.0.3  A pack for the Symfony web profiler
symfony/property-access             v4.1.8  Symfony PropertyAccess Component
symfony/property-info               v4.1.8  Symfony Property Info Component
symfony/routing                     v4.1.8  Symfony Routing Component
symfony/security                    v4.1.8  Symfony Security Component
symfony/security-bundle             v4.1.8  Symfony SecurityBundle
symfony/serializer                  v4.1.8  Symfony Serializer Component
symfony/serializer-pack             v1.0.1  A pack for the Symfony serializer
symfony/stopwatch                   v4.1.8  Symfony Stopwatch Component
symfony/swiftmailer-bundle          v3.2.4  Symfony SwiftmailerBundle
symfony/test-pack                   v1.0.4  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                 v4.1.8  Symfony Translation Component
symfony/twig-bridge                 v4.1.8  Symfony Twig Bridge
symfony/twig-bundle                 v4.1.8  Symfony TwigBundle
symfony/validator                   v4.1.8  Symfony Validator Component
symfony/var-dumper                  v4.1.8  Symfony mechanism for exploring and dumping PHP variables
symfony/web-link                    v4.1.8  Symfony WebLink Component
symfony/web-profiler-bundle         v4.1.8  Symfony WebProfilerBundle
symfony/web-server-bundle           v4.1.8  Symfony WebServerBundle
symfony/webpack-encore-bundle       v1.0.0  Integration with your Symfony app & Webpack Encore!
symfony/yaml                        v4.1.8  Symfony Yaml Component
twig/twig                           v2.5.0  Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                    1.3.0   Assertions to validate method input/output with nice error messages.
zendframework/zend-code             3.3.1   provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager     3.2.1   Trigger and listen to events within a PHP application

**Comment by Rmy5** [comment]
OPCache is active, Nginx returning "bad gateway".
I had to downgrade to 4.1.6.

**Comment by msheakoski** [comment]
@Rmy5 You are still using 4.1.8 which contains the bug. If you update to 4.2.0 by changing your composer.json like https://github.com/symfony/website-skeleton/blob/b5e69337981fdaeab2cc6023c6227b705b46fc62/composer.json#L77 you should not have the issue any longer.

**Comment by Rmy5** [comment]
@msheakoski 
Tried to update to 4.2, but getting another issuer with the translator component:
![cap](https://user-images.githubusercontent.com/30668074/49406297-7c084e00-f755-11e8-8322-febbd52e907a.png)

**Comment by msheakoski** [comment]
`composer require "symfony/translation:*"` should fix it. You need to explicitly add it now. Before, it was added as a dependency of another component, but I am not sure which.

**Comment by Rmy5** [comment]
@msheakoski That fixes it. Tx ! :+1:
