### ISSUE TITLE
[Messenger] Message not sent to AMQP failure transport

### ISSUE THREAD

**Issue by raresserban** [symfony/symfony#31455]
**Symfony version(s) affected**: 4.3-beta1

**Description**  
After handling a message which fails, it will be retried 3 times. If all of those retries fail, then the message should be added to the failure transport (as explained here: https://symfony.com/blog/new-in-symfony-4-3-messenger-failure-transport)
However, for me at least, this is not the case.

I use the following configuration, but after the 3rd retry I can see this in the logs in this order:
`messenger.WARNING: An exception occurred while handling message CLASS... at vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:82 at MY_HANDLER_CLASS.`
`messenger.INFO: Rejected message CLASS will be sent to the failure transport failed.`
`messenger.INFO: Sending message CLASS with "Symfony\Component\Messenger\Transport\AmqpExt\AmqpTransport"...`
`messenger.CRITICAL: Rejecting CLASS (removing from transport). at vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:82 at MY_HANDLER_CLASS`

From what I see, the last `messenger.CRITICAL` error seems to come from the messenger component trying to call my handler again for some reason but I am not sure why. I use routing keys and also amqp for the failed queue, this is my configuration:

```yaml
messenger:
    failure_transport: failed
    transports:
        amqp:
            dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            options:
                exchange:
                    type: topic
                    name: topic
                queues:
                   QUEUE:
                        binding_keys: ['KEY.#']
        failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        type: topic
                        name: topic
                    queues:
                        QUEUE_FAILED:
                            binding_keys: ['#']
```

I am really not sure why this does not work. What I also found out is that when the Symfony\Component\Messenger\EventListener\SendFailedMessageToFailureTransportListener is called, it does not remove the DelayStamp from the envelope, so when the message arrives in the Symfony\Component\Messenger\Transport\AmqpExt\Connection class, the `publishWithDelay` function will be called, which will publish the message again to the delay queue (`delay_queue_KEY.TEST_4000` in this case), with the exchange being `delay` and the routing key `delay_queue_KEY.TEST_4000`. Moreover, the delay queue is setup in the same way, with the routing key being my initial routing key `KEY.TEST` and the exchange name being `topic`, so the message will get published to the `QUEUE` queue not to the `QUEUE_FAILED` queue because of the routing key.

So how can this be prevented?Shouldn't the routing key be set to null before publishing to the `failed` transport, so that way I can put the QUEUE_FAILED to be bound for the null key? Or should I create an AmqpStamp using a middleware in this case, and add a new routing key for the failed transport?But then, why does the `failure_transport` config option even exist if it does not work properly?

**How to reproduce**  
Use routing keys for messages, have the handler fail 3 times and see the results. The message will not be added to the failure transport as intended.

**Possible Solution**  
Ignore all routing keys, exchanges etc when using the `failure_transport` config option when the message fails after the set number of retries, and have the failure_transport and no other transports be used for this situation.

**Comment by Tobion** [comment]
Can you test if it is enough to remove the DelayStamp in the SendFailedMessageToFailureTransportListener?

**Comment by Tobion** [comment]
Or maybe the better solution is to add a new DelayStamp with delay zero. So that the history is kept.

**Comment by raresserban** [comment]
I think I found the problem, according to the RabbitMQ docs, in order for the delay queue to work, there needs to be a subscriber active fore the destination queue:
https://www.cloudamqp.com/docs/delayed-messages.html

So in this case, I need to run the consume command for the failed transport and have it running for this to work.

The fix would be, like @Tobion said, to remove the DelayStamp in this case since it is not needed, since the message will be published to another transport and another queue.

**Comment by weaverryan** [comment]
@raresserban Just to verify that the fix, could you try it?

After this line: https://github.com/symfony/symfony/blob/e19db439d86bce4dd5f6e328cc435702b12e7a42/src/Symfony/Component/Messenger/EventListener/SendFailedMessageToFailureTransportListener.php#L69

Add `->withoutAll(DelayStamp::class)`

That may not be how we actually fix this - but that would verify that we're understanding the problem properly.

**Comment by weaverryan** [comment]
Btw, I added the `DelayStamp(0)` in #31425

**Comment by raresserban** [comment]
Hello, I tested with both `->withoutAll(DelayStamp::class)` and with `DelayStamp(0)` and I seem now to get a weird behavior. Each time the message fails and is added to a delay queue, it is also added to the failed queue.
And the message is for some weird reason processed 8 times instead of the 3 retries, so for one message I have 8 messages in the failed queue.
Might be because of me using routing keys, so maybe I can create a middleware for failed messages and change the routing key for them.

Anyways, the fix you did seems to fix the original issue.

**Comment by weaverryan** [comment]
Indeed, due to your routing keys, I'm not exactly sure what might be going on. What was the reason for adding all `binding_keys`?

**Comment by raresserban** [comment]
I found the problem, is was because I tested with `binding_keys: ['#']`, so all messages published were also published to this queue. I changed this to `binding_keys: ['FAILED.#']` and use a middleware to change the routing key for failed messages.

**Comment by weaverryan** [comment]
Ok great! In general, for future readers, you should not need to do any binding key or routing key setup to get the failure transport to work: it manages setting all of that up correctly internally.

**Comment by shubaivan** [comment]
@raresserban could you provide please middleware example with `middleware` config please ?

**Comment by raresserban** [comment]
@shubaivan 
This is my middleware:
```php
class AmqpMiddleware implements MiddlewareInterface
{
    /**
     * Add the AmqpStamp to envelopes containing a BaseMessage object.
     *
     * @param Envelope $envelope
     * @param StackInterface $stack
     *
     * @return Envelope
     */
    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        $message = $envelope->getMessage();

        if ($message instanceof BaseMessage) {
            $envelope = $envelope->with(
                new AmqpStamp(
                    $message->getRoutingKey(),
                    AMQP_NOPARAM,
                    $message->getAttributes()
                )
            );
        }

        return $stack->next()->handle($envelope, $stack);
    }
}
```

BaseMessage is a DTO which has a routing key and attributes properties.

The middleware is just simply included like in the docs:

```yaml
messenger:
    buses:
        messenger.bus.default:
            middleware:
                - 'Automotive\MessagePublisherBundle\Middleware\AmqpMiddleware'
```

**Comment by shubaivan** [comment]
@weaverryan @raresserban Only when I added 

```
        $envelope = $envelope
            ->withoutAll(AmqpReceivedStamp::class)
            ->with(
            new SentToFailureTransportStamp($event->getReceiverName()),
            new DelayStamp(0),
            new RedeliveryStamp(0, $throwable->getMessage(), $flattenedException)
        );
```

Messages set in failed queue. This my config

```
    messenger:
        buses:
          messenger.bus.default:
            middleware:
              - reply_middleware
        failure_transport: failed

        transports:
          success:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange:
                  type: direct
                  name: productrow
                  default_publish_routing_key: normal
                queues:
                  messages_normal:
                    binding_keys: [normal]
          failed:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange:
                  type: direct
                  name: failed
                  default_publish_routing_key: failed
                queues:
                  messages_failed:
                    binding_keys: [failed]
```

And I not understand what I can do in middlewehere becasue `routing key` private property 

```
class ReplyMiddleware implements MiddlewareInterface
{

    public function handle(Envelope $envelope, StackInterface $stack): Envelope
    {
        $t = 1;
        return $stack->next()->handle($envelope, $stack);
    }
}
```

in `vendor/symfony/messenger/Transport/AmqpExt/Connection.php` routing key get from AmqpStamp

```
    public function publish(string $body, array $headers = [], int $delayInMs = 0, AmqpStamp $amqpStamp = null): void
    {
        $this->clearWhenDisconnected();

        if (0 !== $delayInMs) {
            $this->publishWithDelay($body, $headers, $delayInMs, $amqpStamp);

            return;
        }

        if ($this->shouldSetup()) {
            $this->setupExchangeAndQueues();
        }

        $this->publishOnExchange(
            $this->exchange(),
            $body,
            $this->getRoutingKeyForMessage($amqpStamp),
            $headers,
            $amqpStamp
        );
    }
```

**Comment by shubaivan** [comment]
> ```
>         $message = $envelope->getMessage();
> 
>         if ($message instanceof BaseMessage) {
>             $envelope = $envelope->with(
>                 new AmqpStamp(
>                     $message->getRoutingKey(),
>                     AMQP_NOPARAM,
>                     $message->getAttributes()
>                 )
>             );
>         }
> 
>         return $stack->next()->handle($envelope, $stack);
> ```

@raresserban Thanks you for answer. But this middlewehere is called and when message send, means recieved and when handle messages. In this case message never set in seuccess queue. In your case what means `BaseMessage` and how you manage property routing key in this class ?

**Comment by shubaivan** [comment]
@weaverryan 

I faced with problem with failed queu when using jms serializer, looks stack trace

```
16:10:44 ERROR     [messenger] Error thrown while handling message App\QueueModel\AdtractionDataRow. Sending for retry #1 using 1000 ms delay. Error: "shipping='This value is too short. It should have 2 characters or more.,\nThis value should be equal to "Mary".', manufacturerArticleNumber='This value is too short. It should have 2 characters or more.'" ["message" => App\QueueModel\AdtractionDataRow^ { …},"class" => "App\QueueModel\AdtractionDataRow","retryCount" => 1,"delay" => 1000,"error" => "shipping='This value is too short. It should have 2 characters or more.,\nThis value should be equal to "Mary".', manufacturerArticleNumber='This value is too short. It should have 2 characters or more.'","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
PHP TypeError:  Return value of Symfony\Component\ErrorHandler\Exception\FlattenException::getStatusCode() must be of the type int, null returned in /var/www/symfony/vendor/symfony/error-handler/Exception/FlattenException.php on line 107
PHP Stack trace:
PHP   1. {main}() /var/www/symfony/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/symfony/bin/console:42
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/symfony/vendor/symfony/console/Application.php:140
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:83
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/symfony/vendor/symfony/console/Application.php:264
PHP   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:97
PHP   7. Symfony\Component\Messenger\Command\FailedMessagesRetryCommand->run() /var/www/symfony/vendor/symfony/console/Application.php:930
PHP   8. Symfony\Component\Messenger\Command\FailedMessagesRetryCommand->execute() /var/www/symfony/vendor/symfony/console/Command/Command.php:255
PHP   9. Symfony\Component\Messenger\Command\FailedMessagesRetryCommand->retrySpecificIds() /var/www/symfony/vendor/symfony/messenger/Command/FailedMessagesRetryCommand.php:115
PHP  10. Symfony\Component\Messenger\Command\FailedMessagesRetryCommand->runWorker() /var/www/symfony/vendor/symfony/messenger/Command/FailedMessagesRetryCommand.php:212
PHP  11. Symfony\Component\Messenger\Worker->run() /var/www/symfony/vendor/symfony/messenger/Command/FailedMessagesRetryCommand.php:189
PHP  12. Symfony\Component\Messenger\Worker->handleMessage() /var/www/symfony/vendor/symfony/messenger/Worker.php:81
PHP  13. Symfony\Component\Messenger\Worker->dispatchEvent() /var/www/symfony/vendor/symfony/messenger/Worker.php:130
PHP  14. Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher->dispatch() /var/www/symfony/vendor/symfony/messenger/Worker.php:164
PHP  15. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /var/www/symfony/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:151
PHP  16. Symfony\Component\EventDispatcher\EventDispatcher->callListeners() /var/www/symfony/vendor/symfony/event-dispatcher/EventDispatcher.php:59
PHP  17. Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() /var/www/symfony/vendor/symfony/event-dispatcher/EventDispatcher.php:230
PHP  18. Symfony\Component\Messenger\EventListener\SendFailedMessageForRetryListener->onMessageFailed() /var/www/symfony/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117
PHP  19. Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransport->send() /var/www/symfony/vendor/symfony/messenger/EventListener/SendFailedMessageForRetryListener.php:70
PHP  20. Symfony\Component\Messenger\Transport\Doctrine\DoctrineSender->send() /var/www/symfony/vendor/symfony/messenger/Transport/Doctrine/DoctrineTransport.php:90
PHP  21. Symfony\Component\Messenger\Transport\Serialization\Serializer->encode() /var/www/symfony/vendor/symfony/messenger/Transport/Doctrine/DoctrineSender.php:42
PHP  22. Symfony\Component\Messenger\Transport\Serialization\Serializer->encodeStamps() /var/www/symfony/vendor/symfony/messenger/Transport/Serialization/Serializer.php:102
PHP  23. Symfony\Component\Serializer\Serializer->serialize() /var/www/symfony/vendor/symfony/messenger/Transport/Serialization/Serializer.php:139
PHP  24. Symfony\Component\Serializer\Serializer->normalize() /var/www/symfony/vendor/symfony/serializer/Serializer.php:119
PHP  25. Symfony\Component\Serializer\Serializer->normalize() /var/www/symfony/vendor/symfony/serializer/Serializer.php:156
PHP  26. Symfony\Component\Serializer\Normalizer\ObjectNormalizer->normalize() /var/www/symfony/vendor/symfony/serializer/Serializer.php:146
PHP  27. Symfony\Component\Serializer\Serializer->normalize() /var/www/symfony/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:201
PHP  28. Symfony\Component\Serializer\Normalizer\ProblemNormalizer->normalize() /var/www/symfony/vendor/symfony/serializer/Serializer.php:146
PHP  29. Symfony\Component\ErrorHandler\Exception\FlattenException->getStatusCode() /var/www/symfony/vendor/symfony/serializer/Normalizer/ProblemNormalizer.php:49
PHP TypeError:  Return value of Symfony\Component\ErrorHandler\Exception\FlattenException::getStatusCode() must be of the type int, null returned in /var/www/symfony/vendor/symfony/error-handler/Exception/FlattenException.php on line 107
PHP Stack trace:
PHP   1. {main}() /var/www/symfony/bin/console:0
PHP   2. Symfony\Bundle\FrameworkBundle\Console\Application->run() /var/www/symfony/bin/console:42
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/symfony/vendor/symfony/console/Application.php:140
PHP   4. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:83
PHP   5. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/symfony/vendor/symfony/console/Application.php:264
PHP   6. Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() /var/www/symfony/vendor/symfony/framework-bundle/Console/Application.php:97

In FlattenException.php line 107:
                                                                                                                       
  Return value of Symfony\Component\ErrorHandler\Exception\FlattenException::getStatusCode() must be of the type int,  
   null returned                                                                                                       
                                                                                                                       

messenger:failed:retry [--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<id>...]
```

**Comment by jmhoueg** [comment]
@raresserban i'm facing the same problem as you did, is it possible to send me everything you did in your middleware and config since i'm trying to reproduce what was said above but when i send to the failed queue, there are auto retries but i dont want to. Can you help me please?

**Comment by raresserban** [comment]
@jmhoueg Hey, I no longer work on the project so I don't have access to the old code. My problems were also related to an older version of the messenger component, I believe in Symfony 4.4 and up the problem is fixed and the failed queue works properly.
You can configure the retries from the config I believe, please check the documentation:
https://nickis.atlassian.net/browse/DEV20-146

**Comment by jmhoueg** [comment]
Hello @raresserban thx for your quick answer. I'm using the latest version of the messenger component in Symfony 5.1 but still have problems with the failed queue and RabbitMQ and binding keys. Can't access the link you sent me, i don't have the rights but thx though

**Comment by raresserban** [comment]
@jmhoueg Sorry, I can't copy paste for some reason, link updated :)

**Comment by jmhoueg** [comment]
No worries. Tried everything in the docs but it's with the failed queue that i'm having trouble

**Comment by musahaidari** [comment]
For me setting the queues property explicitly for failed transport worked (with AMQP, symfony 6):

```
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: failed
                    queues:
                        failed_messages: ~
```

**Comment by issam-chouchane** [comment]
> class ReplyMiddleware implements MiddlewareInterface
> {
> 
>     public function handle(Envelope $envelope, StackInterface $stack): Envelope
>     {
>         $t = 1;
>         return $stack->next()->handle($envelope, $stack);
>     }
> }

Can you send main classes that you implements in your exemple ?

Thnx
