### ISSUE TITLE
PHP 7.1.30 segfault on commit [DI] fix dumping inlined services in class PhpDumper

### ISSUE THREAD

**Issue by armetiz** [symfony/symfony#32852]
**Symfony version(s) affected**: 3.4.19

**Description**  
When trying to upgrade Symfony to the last 3.4 version, I'm getting a segfault when reaching v3.4.19.
After a git bisect session, the first bad commit is [[DI] fix dumping inlined services](https://github.com/symfony/symfony/commit/a97606d58aa9686c5d973351e8e6c93285110878)

There is no segfault when using symfony/symfony:v3.4.30 with PhpDumper:3.4.18.

**How to reproduce**  

Install symfony/symfony:v3.4.19 with the following stack.

```
PHP 7.1.30 (cli) (built: Jul  2 2019 17:22:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.30, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.26.3~linux-x64-non_zts71, https://blackfire.io, by Blackfire
```

```
[PHP Modules]
apcu
bcmath
blackfire
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
blackfire
```

**Comment by dmaicher** [comment]
So its working fine with `3.4.30`? is there something we need to fix then?

**Comment by armetiz** [comment]
@dmaicher as I said; segfault symfony >=v3.4.19.

Thanks to git bisect, I can tell you that segfault have been introduced by https://github.com/symfony/symfony/commit/a97606d58aa9686c5d973351e8e6c93285110878

-----

I did some tests

symfony >= v3.4.19
```
composer require symfony/symfony:3.4.18 # no segfault when clearing cache
composer require symfony/symfony:3.4.19 # segfault when clearing cache
composer require symfony/symfony:3.4.30 # segfault when clearing cache
```

Install symfony:3.4.30 using `PhpDumper:3.4.18`.

```
composer require symfony/symfony:3.4.30 --prefer-source # segfault when clearing cache
cd vendor/symfony/symfony
git checkout v3.4.18 src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
../../../app/console cache:clear # no segfault, this is working !!
```

**Comment by nicolas-grekas** [comment]
Fixed already, see https://twitter.com/nicolasgrekas/status/1155890784245309441

**Comment by armetiz** [comment]
Hi @nicolas-grekas 
segfault still occurred with `v3.4.*@dev`.

```
cd ./vendor/symfony/symfony
git fetch -p
git checkout 3.4; git pull
./../../app/console cache:clear # segfault
git checkout v3.4.18 src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php
./../../app/console cache:clear # no segfault, this is working !!
```

**Comment by nicolas-grekas** [comment]
Can you please provide a reproducer?

**Comment by armetiz** [comment]
OK I've found the problem.
One of our class need itself to be constructed. I don't know how it could work <= v3.4.18.

I've debugged PhpDumper using https://jolicode.com/blog/find-segfaults-in-php-like-a-boss & var_dump ..

The class specs were 
```php
class SegFault extends AbstractClass
{
  public function __construct(Service $service, SegFault $segFault, Manager $manager)
  {
    $this->service = $service;
    $this->segFault = $segFault;
    $this->manager = $manager;

    parent::__construct();
  }
}
```


I don't know If the class specification is enough to reproduce the issue. But if yes; a friendly error message could be really useful.

King regards;
Thomas.



```

```

**Comment by nicolas-grekas** [comment]
@armetiz could you please send the reproducer as a small application we could run locally to play with this issue?

**Comment by armetiz** [comment]
@nicolas-grekas 

* DIC autoconfigured on
* DIC autowired on

A class like the following

```
class SegFault extends AbstractClass
{
  public function __construct(Service $service, SegFault $segFault, Manager $manager)
  {
    $this->service = $service;
    $this->segFault = $segFault;
    $this->manager = $manager;

    parent::__construct();
  }
}

class Manager
{
  public function foo(): string { return "bar" }
}

class Service
{
  public function john(): string { return "doe" }
}
```

**Comment by stof** [comment]
this is still not a full repoducer, as `AbstractClass` is not part of if.

**Comment by armetiz** [comment]
I agree; sorry but after one month I forget about the use-case.

**Comment by xabbuh** [comment]
Let's close here then. We can reopen in the future if we are able to reproduce.
