### ISSUE TITLE
Bug of end of line using  Yaml::dump

### ISSUE THREAD

**Issue by abonne01** [symfony/symfony#33464]
**Symfony version(s) affected**: 4.3.4
**Description**  
Following correction of bug #32251 (thanks @nicolas-grekas) there is a problem with yaml::dump function when using Tagged value and inline parameter

**How to reproduce**  
```php
    $rootYaml[] = new TaggedValue('group', 'admin');
    $rootYaml[] = new TaggedValue('group', 'admin2');
    $admin = array(
        'role' => new TaggedValue('group', 'admin'),
        'privileges' => array('read', 'create', 'update'),
        'resource' => new TaggedValue('policy', 'root')
    );
    $rootYaml[] = new TaggedValue('permit', $admin);

    $value = Yaml::dump($rootYaml, 3);
    print_r($value);
    
```

**result**  

```yaml
- !group
  admin- !group
  admin2- !permit
  role: !group
      admin  privileges:
      - read
      - create
      - update
  resource: !policy
      root
```

**expected result**  
```yaml
- !group admin
- !group admin2
- !permit
  role: !group admin  
  privileges:
      - read
      - create
      - update
  resource: !policy root
```

**Comment by xabbuh** [comment]
Is this the same as #33354 and thus fixed by #33377?

**Comment by abonne01** [comment]
Hello,

I applied fixed on my test. it's already much better but doesn't solve completely:
This is result with fix. For me there are now too many end lines.
```yaml
- !group
  admin
- !group
  admin2
- !permit
  role: !group
      admin
  privileges:
      - read
      - create
      - update
  resource: !policy
      root
```

**Comment by abonne01** [comment]
After additional checks, it seems that both syntax are valid (not a yaml expert).
Tt least, application used (conjur) accept both syntax.

I feel that it's more human readable in one line for such cases:

```yaml
- !group
  admin
```
or
```yaml 
- !group admin
```

**Comment by xabbuh** [comment]
Before the latest release the dumper didn't take the inline argument into account when dumping tagged values. That's the explanation for the difference if I don't miss anything else.

**Comment by xabbuh** [comment]
@abonne01 I guess #33518 is what you have in mind, right?

**Comment by abonne01** [comment]
perfect. #33518 solve  issue. Thanks.
