### ISSUE TITLE
[FrameworkBundle] Unable to remove deprecation notice in FileLocator?

### ISSUE THREAD

**Issue by acasademont** [symfony/symfony#34556]
**Symfony version(s) affected**: 4.4.0
**Description**  
When running our test suite we saw this deprecation notice:

`
2x: Loading the file "../src/UI/Http/Web/Controller/" from the global resource directory "/app/src" is deprecated since Symfony 4.4 and will be removed in 5.0.
`

...that we can't really remove, the FrameworkBundle is injecting the `$paths` parameter to the `FileLocator` service and our routes.yaml resource, configured this way according to the docs:

```
web_controllers:
    resource: '../src/UI/Http/Web/Controller/'
    type: annotation
```

...is the one triggering this notification. AFAIK, this way of configuring the routes with relative paths is still the recommended way, but the deprecation notice seems to trigger whenever there's a non-absolute path being loaded, even though it doesn't use the deprecated `$paths` variable in order to be located, which I believe is a little bit too extreme?

**Comment by mhujer** [comment]
I'm getting those as well but in a bit different context: `Loading the file "../../src/" from the global resource directory "C:\dev\htdocs\project\src" is deprecated since Symfony 4.4 and will be removed in 5.0.`

In my projects I'm not grouping classes by their type - `Controller`, `FormType`, but by their _domain_, so I need to search through the whole `src` directory for the controllers. My `config/routes/annotations.yaml` looks like this:

```
controllers:
    resource: ../../src/
    type: annotation
```

Releated PR https://github.com/symfony/symfony/pull/33258
Releted Issue: https://github.com/symfony/symfony/issues/31915

**Comment by ruudk** [comment]
Same issue here with SF 4.4.0:
```yaml
# config/routes.yaml
infrastructure:
    resource: '../src/Infrastructure/Controller/'
    type: annotation
    defaults: { _format: 'json' }
```

```
User Deprecated: Loading the file "../src/Infrastructure/Controller/" from the global resource directory "/var/www/app/src" is deprecated since Symfony 4.4 and will be removed in 5.0. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Loading the file \"../src/Infrastructure/Controller/\" from the global resource directory \"/var/www/app/src\" is deprecated since Symfony 4.4 and will be removed in 5.0. at /var/www/app/vendor/symfony/http-kernel/Config/FileLocator.php:73)"} [] 
```

**Comment by k00ni** [comment]
Same here:

```
Loading the file "../../src/App/Controller/" from the global resource directory 
"/var/www/html/src/App" is deprecated since Symfony 4.4 and will be removed in 5.0.
```

But  related configuration is located in `config/routes/annotations.yaml` and not `config/routes.yaml`, as posted by @ruudk. I am not sure, if that is relevant.

```yaml
# config/routes/annotations.yaml
controllers:
    resource: ../../src/App/Controller/
    type: annotation
```

Can anyone explain why this behavior was deprecated? Could not find a *deprecations* page for Symfony 4.4, except one with [new features](https://symfony.com/blog/symfony-4-4-curated-new-features). Thank you.

**Comment by mhujer** [comment]
@k00ni What did you find? I found just this, which does not seem that much related:

> Deprecated loading resources from %kernel.root_dir%/Resources and %kernel.root_dir% as fallback directories.

**Comment by k00ni** [comment]
To be honest, i don't know how i "fixed" it. Sorry.

I got another deprecation's besides the one i mentioned, like 

`The "twig.controller.exception" service is deprecated since Symfony 4.4.`

I guess after fixing it like described [here](https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#twigbundle) (first entry `twig.exception_controller`) and removing the cache `var/cache/dev`, the resource annotation was gone.

**Comment by acasademont** [comment]
They are not related at all, we're not even using Twig.

@mhujer yes, that's the relevant info, but the deprecation notice triggers more often than it should.

**Comment by spipu** [comment]
i've the same issue : 

`User Deprecated: Loading the file "../../src/App/Controller/" from the global resource directory "/var/www/symfonydev/website/src/App" is deprecated since Symfony 4.4 and will be removed in 5.0.`

from this file : ./config/routes/annotations.yaml

there is nothing to do to avoid having this deprecated notice ?

**Comment by acasademont** [comment]
@spipu not yet. Maybe @Tobion can help us here, the deprecation notice probably needs another condition to fire

**Comment by frankdekker** [comment]
Not the best solution but I've "fixed "it by changing the annotations.yaml to annotations.php notation and force the path to an absolute path.

**Before:**
annotations.yaml
```
controllers:
    resource: ../../src/Controller/
    type: annotation
```


**After**
annotations.php
```
<?php
declare(strict_types=1);

$path = dirname(__DIR__, 2) . '/src/Controller/';

return $loader->import($path, 'annotation');
```

**Comment by jdsaphir** [comment]
I get this deprecation as soon as Symfony 4.4 is installed, I don't really understand how this went unnoticed. I've "fixed" it too just by adding an asterisk at the end of the resource line in `annotations.yaml`.

**Before:**
```YAML
controllers:
    resource: ../../src/Controller/
    type: annotation
```

**After:**
```YAML
controllers:
    resource: ../../src/Controller/*
    type: annotation
```

**Comment by xabbuh** [comment]
> I don't really understand how this went unnoticed.

I don't see anyone reporting this before the release of 4.4.0 and 5.0.0.

**Comment by acasademont** [comment]
@jdsaphir i'm afraid this doesn't fix the issue for me, it breaks all routing

**Comment by jdsaphir** [comment]
> @jdsaphir i'm afraid this doesn't fix the issue for me, it breaks all routing

@acasademont Weird, it works for me...

4.4.1 doesn't solve this btw.

**Comment by xabbuh** [comment]
Can anyone of you create a small example application that allows to reproduce this?

**Comment by acasademont** [comment]
@xabbuh any simple symfony standard app with the routes.yaml posted by any of us triggers the notification on the first container compilation. After that, the routes are already cached and the deprecation doesn't trigger anymore

**Comment by xabbuh** [comment]
I am not able to reproduce. You can take a look at my attempts at https://github.com/xabbuh/issue-34556. Please feel free to make the changes that are required to reproduce it.

**Comment by acasademont** [comment]
@xabbuh yes it does, just start the symfony server `symfony serve` and load the initial page, then just go to the web toolbar to see the deprecations triggered and you wil see it

<img width="1068" alt="Screenshot 2019-12-02 at 10 56 03" src="https://user-images.githubusercontent.com/825021/69949831-838e3e80-14f2-11ea-8edf-4c0a9231f1be.png">

**Comment by xabbuh** [comment]
Thanks, I am able to reproduce it now. Looking into it.

**Comment by xabbuh** [comment]
I think #34886 should solve this.

**Comment by k00ni** [comment]
Will the fix #34886 solve the following deprecation on its own or does one has to adapt something in the YAML/PHP Code?

> Loading the file "../../src/App/Controller/" from the global resource directory 
"/var/www/html/src/App" is deprecated since Symfony 4.4 and will be removed in 5.0.

**Comment by acasademont** [comment]
I can confirm the fix works, awesome :)

**Comment by xabbuh** [comment]
@k00ni yes, that should be fixed too

**Comment by relm** [comment]
I'm still getting these depreciation notices in 4.4.2 under certain conditions.  If I clear cache, the notices no longer show. But when I run:

`php bin/console cache:warmup`

Then visit a page on the site these depreciation notices will show. So for some reason, warming up the cache causes these notices to show again. This only happens in dev also, I couldn't reproduce it under prod.

My routes.yaml looks like this:

```
api_partner:
    host: '%baseApiHost%'
    type: rest    # This resource will have RESTful routes
    resource: '../src/Controller/ApiPartner'
    name_prefix: partner_api_  # RestBundle-specific prefixes are allowed now, as the RestBundle is now processing routes
```

```
Loading the file "../src/Controller/ApiPartner" from the global resource directory "/media/psf/project/symfony/src/Resources" is deprecated since Symfony 4.4 and will be removed in 5.0.
```

**Comment by xabbuh** [comment]
@relm Please open a new issue and provide a small example application that allows to reproduce.

**Comment by fancyweb** [comment]
@relm You might have the same misconfiguration that I had: a routing file in a subdirectory of `config` (eg: `config/routes/foo.yaml`) that references a directory or a file of `src` relatively  but  that misses  a `..` (eg: `../src/Controller/Foo` instead of `../../src/Controller/Foo`).

In this case, the file is still found by the `FileLocator` but only thanks to the global resource directory `src`. The fact that the message mentions `Resources` is a bug that will be resolved by https://github.com/symfony/symfony/pull/35269. But the deprecation should still be triggered, your code is probably the problem here.
