### ISSUE TITLE
[Translation] Push command error

### ISSUE THREAD

**Issue by DevScyu** [symfony/symfony#41501]
**Symfony version(s) affected**: 5.3.x

**Description**
Error message about missing config when config in place.

Edit: Config does not seem to be read properly for domains and locales at all, it only uses the command line inputs

**How to reproduce**
Copy the example from https://symfony.com/doc/current/translation.html#translation-providers and run `php bin/console translation:push loco --force`

**Possible Solution**
This either needs to check `framework.translator.providers.%s.locales` or remove it from the error message.

Edit: Add config checks for domains and locales 

**Additional context**
https://github.com/symfony/translation/blob/251de0d921c42ef0a81494d8f37405421deefdf6/Command/TranslationPushCommand.php#L97-L99

Edit: https://github.com/symfony/translation/blob/251de0d921c42ef0a81494d8f37405421deefdf6/Command/TranslationPushCommand.php#L103-L105

**Comment by stof** [comment]
I think that this might miss a `sprintf`

/cc @welcoMattic

**Comment by DevScyu** [comment]
Upon looking at the translation push command further, it does not read the config at all it seems, just the command line inputs.

**Comment by welcoMattic** [comment]
I think we miss something here https://github.com/symfony/symfony/blob/3b197fe9bf6f322e3433540b842209b718623063/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/FrameworkExtension.php#L1367-L1380

@stof I fixed the missing `sprintf`, thanks, I will push it with the fix of this issue. I'm working on it.

**Comment by welcoMattic** [comment]
@DevScyu I think this fix should work, as `framework.translator.enabled_locales` is not mandatory anymore, we will use `framework.translator.providers.loco.locales` as fallback. Could you try it?

**Comment by DevScyu** [comment]
> @DevScyu I think this fix should work, as `framework.translator.enabled_locales` is not mandatory anymore, we will use `framework.translator.providers.loco.locales` as fallback. Could you try it?

This works for the locale option from the config now, but still not working for domains.

**Comment by welcoMattic** [comment]
@carsonbot could you tag this issue as a bug? cc/ @Nyholm
