### ISSUE TITLE
[6.3.beta1] lint:container command reports errors

### ISSUE THREAD

**Issue by COil** [symfony/symfony#50234]
### Symfony version(s) affected

6.3.beta1

### Description

```
[ERROR] Invalid definition for service "debug.argument_resolver.request_payload": argument 1 of
         "Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestPayloadValueResolver::__construct()" accepts
         "Symfony\Component\Serializer\SerializerInterface&Symfony\Component\Serializer\Normalizer\DenormalizerInterface
         ", "Symfony\Component\Serializer\Serializer" passed.
```

### How to reproduce

`bin/console lint:container`

**Comment by PhilETaylor** [comment]
Tried to replicate on my large app and it worked fine. 

<img width="1060" alt="ScreenShot-2023-05-04-12 25 32" src="https://user-images.githubusercontent.com/400092/236190697-ba33bea1-fb5e-4e49-83eb-bcc66aef4b42.png">

**Comment by MatTheCat** [comment]
@COil which version of PHP are you running `bin/console lint:container` with?

**Comment by COil** [comment]
`8.1.17`

https://github.com/strangebuzz/MicroSymfony/actions/runs/4879224143/jobs/8705590506

**Comment by MatTheCat** [comment]
Okay thanks for the reproducer; the issue seems to arise because the serializer is not installed.

**Comment by stof** [comment]
The RequestPayloadValueResolver service should probably not be registered when the serializer is not enabled in the project

**Comment by nicolas-grekas** [comment]
An errored definition is wired on purpose when the serializer is missing. I think the proper fix might be to skip checking errored definitions in `CheckTypeDeclarationsPass`. The type doesn't matter anyway since those definitions always throw.
PR welcome (on 5.4 I guess since this is a bugfix)

**Comment by MatTheCat** [comment]
~`RequestPayloadValueResolver` would be instantiated through `ArgumentResolver` so I guess there are two different issues?~

**Comment by stof** [comment]
Well, if CheckTypeDeclarationsPass does not skip errored definitions, that's indeed the issue

**Comment by MatTheCat** [comment]
Seems it does: https://github.com/symfony/symfony/blob/f1122a2ab2b8235e2f394b8d15468c363b324043/src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php#L87-L89

But `RequestPayloadValueResolver`’s definition has no error.

**Comment by nicolas-grekas** [comment]
It's first arg is (it's an inlined definition)

**Comment by MatTheCat** [comment]
Oh okay the fix would be around https://github.com/symfony/symfony/blob/f1122a2ab2b8235e2f394b8d15468c363b324043/src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php#L212 then? Can work on it.

**Comment by MatTheCat** [comment]
Just discovered the issue only manifests on debug mode so it seems to be linked on how `ContainerLintCommand` build the container.

**Comment by stof** [comment]
@MatTheCat what is not skipped is cases where arguments receive an errored definition. The validation error you get is when processing the definition for `RequestPayloadValueResolver`, not the errored definition that is injected into it.
Each type check for an argument involves *2* definitions. The one being checked and the one being injected inside it. And only of of them is checked for errors.

**Comment by MatTheCat** [comment]
Okay so the fix would be to add a check for errors after https://github.com/symfony/symfony/blob/f1122a2ab2b8235e2f394b8d15468c363b324043/src/Symfony/Component/DependencyInjection/Compiler/CheckTypeDeclarationsPass.php#L212

But it would not work on debug mode when the cache is fresh, because then  `ContainerLintCommand` builds the container using its XML dump which cannot define errors. A solution exists in the form of services name starting with `.errored.` but it cannot be used to skip arguments since the ID is not accessible from the definition :thinking:

**Comment by MatTheCat** [comment]
From my limited PoV the best solution would be to remove this check https://github.com/symfony/symfony/blob/1b66735850c90c06df2c1b4c223515a862cffd31/src/Symfony/Bundle/FrameworkBundle/Command/ContainerLintCommand.php#L91 and never build the container from the XML dump.

Is there a better alternative? I guess allowing users to add errors to definitions is not an option?

**Comment by PhilETaylor** [comment]
Interestingly I just composer update with 6.3.x-dev and now I get this message, slightly different, not mentioning Serialiser but this time EventSubscriberInterface

To be clear symfony/serializer 6.3.x-dev *IS ALSO* installed

<img width="1143" alt="ScreenShot-2023-05-06-13 48 02" src="https://user-images.githubusercontent.com/400092/236625083-c4834de6-f0b2-491b-920c-05092939a1c1.png">

**Comment by nicolas-grekas** [comment]
Fixed in #50260, thanks for the report.

**Comment by MatTheCat** [comment]
If I’m not mistaken there’s still an issue with `lint:container` when run in debug mode with a fresh cache, cf. https://github.com/symfony/symfony/issues/50234#issuecomment-1536332905

**Comment by nicolas-grekas** [comment]
I think I fixed this aspect too. Please check #50260

**Comment by MatTheCat** [comment]
Sorry didn’t realize the root cause was the same :sweat_smile: 

Could #50260 replace the `.errored.` prefix “hack”?

**Comment by nicolas-grekas** [comment]
Sure, PR updated.

**Comment by COil** [comment]
Just to confirm, it's now OK with BETA3.
