### ISSUE TITLE
[Validator] Structure of BIC changed with ISO 9362:2022

### ISSUE THREAD

**Issue by luxemate** [symfony/symfony#51975]
### Symfony version(s) affected

all

### Description

I have found some [preview](https://cdn.standards.iteh.ai/samples/84108/21078408ed25469391d0cf6c5d1b6ca9/ISO-9362-2022.pdf) of the new standard, which can be interpreted as:
> Party prefix is 4 upper-case **alphanumeric** characters (A to Z and 0 to 9 only)

We found out about the issue in production, because someone was tying to use an IBAN from UAE bank, which has BIC E097AEXXXXX.

### How to reproduce

Use BIC E097AEXXXXX with the `BicValidator`.

### Possible Solution

Use `ctype_alnum` for the first 4 characters.

#### Proof from iban.com
![image](https://github.com/symfony/symfony/assets/1465003/9a503fa3-d12b-4cfd-b29f-68519dc4671b)

#### Element description from the updated standard
![image](https://github.com/symfony/symfony/assets/1465003/4a15ab9a-e000-408e-8761-2871652dfe1c)

#### Conventions used in the format column
The following conventions are used in this document:

1. character representations:
    * a: upper-case letters (alphabetical characters A to Z only);
    *  n: digits (numeric characters 0 to 9 only);
    *  c: upper-case alphanumeric characters (A to Z and 0 to 9 only).
2. length indications:
    * nn!: fixed length;
    *  nn: maximum length.

**Comment by OskarStark** [comment]
friendly ping @mvhirsch as you contributed the `BicValidator` IIRC

**Comment by mvhirsch** [comment]
The validator was implemented using the _ISO 9362:2014_ standard, because I implemented it back in 2015. I'm happy to see updates, but I do not have access to any official document for _ISO 9362:2022_. The _ISO 9362:2014_ described the first 4 characters to be alphabetical only, IIRC. 

According to [ISO Database (OBP)](https://www.iso.org/obp/ui/en/#iso:std:iso:9362:ed-5:v1:en): 

> the style of the BIC structure in Clauses 4 and 5 has been aligned with the style used in the ISO 17442 series;

I don't know the _ISO 17442_ either, making it hard for me giving any advice on this.

----

Sadly the BIC isn't officially registered by SWIFT (maybe a "non-connected" BIC?): https://www2.swift.com/bsl/?bicSearch_bic=E097AEXXXXX

No validator I tried on the internet is able to validate it. According to some research, it may seem to be the _Al Maryah Community Bank_, which [itself states it's BIC](https://www.mbank.ae/about/) is _E097AEXX_ (using the 8 chars variant). This is BIC is also invalid as the above according to the `BicValidator`.

Without access to official documents I can not recommend anything from my side.

**Comment by luxemate** [comment]
@mvhirsch I've provided a link to a preview of ISO 9362:2022 in the first message. Not sure how legit is it, but looks like one. I've also found info on SWIFT website (https://www.swift.com/standards/data-standards/bic-business-identifier-code) that states:

>The BIC is an 8 character code, defined as ‘business party identifier’, **consisting of the business party prefix (4 alphanumeric)**, the country code as defined in ISO 3166-1 (2 alphabetic), and the business party suffix (2 alphanumeric).
>
>The branch identifier is a 3 character optional element that can supplement the 8 character BIC, used to identify specific locations, departments, services or units of the same business party.

Is it official enough?

**Comment by mvhirsch** [comment]
I just implemented your suggestion, it now fails on previously valid BICs within the test cases.

SWIFT refers to the ISO 9362. As I stated above: without access to that document, I'm not able to help you here.

Neither I can access a big trusted & validated BIC database after so many years. I'm really not able to help here (beside the fact I can manage a code review, if you provide a PR).

**Comment by derrabus** [comment]
Apparently, the validator needs an update. I've added the "help wanted" label.

If someone needs this validator to be updated, please have have a look behind that 40 CHF paywall and send a PR.

**Comment by Seb33300** [comment]
> If someone needs this validator to be updated, please have have a look behind that 40 CHF paywall and send a PR.

I think you forgot to provide the link?
https://www.iso.org/standard/84108.html

**Comment by maxbeckers** [comment]
As far as I know it was not used for a long time, but it was already defined in ISO-9362-2014 that the first 4 characters of the BIC may also contain numbers.

**Comment by MatTheCat** [comment]
Okay don’t ask me how I found it but the change from alphabetic to alphanumeric four first characters comes from the second edition (from 1994).

ISO 9362:2022 says a valid BIC contains

- 4 upper-case alphanumeric characters (party prefix)
- 2 upper-case letters (country code)
- 2 upper-case alphanumeric characters (party suffix)

These three parts form a business party identifier.

It can then be followed by 3 upper-case alphanumeric characters (branch identifier).

---

From https://www.swift.com/swift-resource/9586/download:

> SWIFT, as RA, has no plan to issue BICs with
numeric characters in the first 4 characters.
>
> If applications have implemented restrictions
on the allowed characters, it would be good
practice to remove this restriction at the
occasion of a software update to respect the
standard specification of 4 alpha-numeric
characters.

Maybe there can be other Registration Authorities outside of ISO ¯\\\_(ツ)_/¯

---

Implementation-wise, this means the `ctype_alpha` check on the four first characters can be removed (since the whole BIC is checked by `ctype_alnum`).

Removing a check means that BICs previously considered valid would still be. However, `Bic::INVALID_BANK_CODE_ERROR` would then become useless, and data sets expecting this code valid.
