### ISSUE TITLE
[Form] broken submit behavior with zero indexed collection items.

### ISSUE THREAD

**Issue by jan-pintr** [symfony/symfony#52318]
### Symfony version(s) affected

6.3.6

### Description

https://github.com/symfony/symfony/pull/52021 introduced an issue when form collection contains zero indexed item.

When submitting form with zero indexed collection item its values are reindexed.

There was an attempt to fix this in [b769b77](https://github.com/symfony/symfony/commit/b769b779fe09e6cdb6e27a5b5185487902817c2a) but it was not enough for this case. As the original issue is closed. There is new one.

### How to reproduce

See reproducer with test case and proposed change: 
https://github.com/symfony/symfony/compare/6.4...jan-pintr:symfony-form-zero-indexed-collection-reporoducer:form-zero-indexed-col-reproducer?expand=1

### Possible Solution

Reproducer contains proposed change to `FormUtil::mergeParamsAndFiles()` function.

**Comment by xabbuh** [comment]
Can you please check if this is the same as (or similar to) #52248 and was also fixed by #52255?

**Comment by jan-pintr** [comment]
It is pretty much same as [#52248](https://github.com/symfony/symfony/issues/52248) but this case was not fixed by [#52248](https://github.com/symfony/symfony/issues/52248) or [#52255](https://github.com/symfony/symfony/pull/52255).

**Comment by nicolas-grekas** [comment]
Can you please send a PR so that we can discuss on the patch?
