### ISSUE TITLE
[DependencyInjection] Warn when not using `bool` environment processor on `bool` argument together with `#[Autowire(env: 'ENV')]`

### ISSUE THREAD

**Issue by ruudk** [symfony/symfony#53918]
### Description

We had an interesting issue today where we deployed the following code:

```php
final class ServiceName
{
    public function __construct(
        #[Autowire(env: 'SANDBOX')]
        public bool $sandbox,
    ) {}
}
```

And set the following in our `.env`:
```env
SANDBOX=false
```

The `$sandbox` property in `ServiceName` was set to `true`.

It took us a while to understand what went wrong here. Because `false` is seen as true-ish, it became `true`. 

We missed the `bool` environment processor. Changing it to `#[Autowire(env: 'bool:SANDBOX')]` solved it. So it was just a mistake on our end.

But that lead me to wonder: why can't Symfony warn me about this? Given that I use Autowire, it already knows that I'm targeting a boolean property. It would be great if it would say something like:

```
Warning: You should use the `bool` environment processor for `$sandbox` in `ServiceName`.
```

If you think this is a valid idea, what would be the best location to implement this check?
Somewhere around here? 
https://github.com/symfony/symfony/blob/ba614efabe5dbbdce071a69ec68a1cc891069336/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php#L309-L310

**Comment by derrabus** [comment]
I understand what you're trying to do here, I think. But we need to be aware that anyone could define their own env processor that returns booleans. Just checking for the `bool` processor could result in many false positives.

Can we detect the implicit cast at runtime maybe?

**Comment by ruudk** [comment]
> But we need to be aware that anyone could define their own env processor that returns booleans. Just checking for the bool processor could result in many false positives.

I see, what if we make a "dumb" rule that checks if there are **no** environment processors defined? So a raw `KEY_NAME`. In that case, it  can trigger a warning?

> Can we detect the implicit cast at runtime maybe?

I'd like to know this at compile time / CI.

**Comment by derrabus** [comment]
> > Can we detect the implicit cast at runtime maybe?
> 
> I'd like to know this at compile time / CI.

Maybe that's could be solved by static analysis instead?

* https://github.com/phpstan/phpstan-symfony
* https://github.com/psalm/psalm-plugin-symfony

**Comment by ruudk** [comment]
Sure, that's a way. I was just raising this issue because I'm confident more people are bitten by this, or will get bitten by this in the future 😅 Would be great if Symfony could help a little bit preventing the obvious problem (bool + without an env processor)

**Comment by nicolas-grekas** [comment]
What about adding the prefix automatically?
`Autowire(env: foo)` on a boolean argument would become `Autowire(env: 'bool:foo')` internally? This would still be compatible with custom processors.

**Comment by ruudk** [comment]
Yeah that would be great. 

What would be the best way to do that? I could try to create a PR f or that.

**Comment by nicolas-grekas** [comment]
That'd be in AutowirePass I suppose.

**Comment by ruudk** [comment]
Created a PR:
- https://github.com/symfony/symfony/pull/53971

**Comment by pkly** [comment]
We have also just hit an issue on prod related to this, so yeah, a warning or automatic configuration would be nice.

**Comment by ro0NL** [comment]
isnt this easily solved with `declare(strict_types=1);` everywhere :')

**Comment by ruudk** [comment]
> isnt this easily solved with `declare(strict_types=1);` everywhere :')

In Symfony you mean? Because in our project we do that already. It doesn't solve it.

**Comment by ro0NL** [comment]
But who's casting then :confused: https://3v4l.org/VKK6n
