### ISSUE TITLE
Stateless CSFR not working with mixed forms in app - some within turbo frames and some outside turbo frames

### ISSUE THREAD

**Issue by zalesak** [symfony/symfony#59571]
### Symfony version(s) affected

7.2.2

### Description

When you are using forms only inside turbo frames - stateless CSFR validate origin info.
When you are outside turbo-frames - stateless CSFR validate token and origin.

But when there is combination - after first non-turbo-frame submit, statless CSFR stop working on turbo-frame submits with CSRF validation accepted using both origin and double-submit info.

### How to reproduce

1. Activate statless CSFR
2. submit form with csfr active outside turbo-frame or with data-turbo-frame="_top"
3. submit another form inside turbo-frame

Form is not validated because of CSFR.

### Possible Solution

Hotwired turbo not firing submit event when form is submitted inside frame. So there is no CSFR token in form field (csrf_protection_controller run only submit-start and submit-end event listeners).

When all forms are submitted within frames, SameOriginCsrfTokenManager notes into session that double submit is not available and eveyrting works. But after first submit outside turbo frame - SameOriginCsrfTokenManager notes into session that there is double submit and therefore stopped working inside turbo frame.

I think it is necessary modifiy csrf_protection_controller to work with and without submit event.

**Comment by nicolas-grekas** [comment]
Can you please provide a small app that'd reproduce the issue, with a readme to make it easy for us?

**Comment by zalesak** [comment]
Here it is
https://github.com/zalesak/stateless-csrf-bug-demonstration

**Comment by nicolas-grekas** [comment]
Thanks. Looks like this was fixed by https://github.com/symfony/recipes/pull/1375/files#diff-a92209d6ca70e2bd935a6eb29f494d2b409f3980cb50a29cb94dac0c418900dbR7

Can you please confirm you don't see the issue anymore after getting the file from the updated recipe?

**Comment by zalesak** [comment]
It has been fixed, thank you!

**Comment by Maxi-M** [comment]
The same issue happened in my case even with the above mentioned fix.

The problem is not permanent, but appears under certain condition with CRUD setup:
1. At index page make a full page refresh.
2. Navigate to edit page.
3. Try to submit. It fails with the csrf error.
4. At the same edit page make a full refresh again, now submit succeeds. 

I noticed this bug goes away if /* stimulusFetch: 'lazy' */ is removed from the csrf-protection-controller

**Comment by nicolas-grekas** [comment]
This has been fixed recently AFAIK

**Comment by Maxi-M** [comment]
> This has been fixed recently AFAIK

I was trying to update the recipe, today. It didn't fix the issue.

**Comment by smnandre** [comment]
I believe this was fixed recently in the 2.x-dev branch of SymfonyUX / StimulusBundle:  https://github.com/symfony/ux/pull/2590

We will probably release a new version next week.

Can you check the PR and tell me if this is good for you ?

**Comment by Maxi-M** [comment]
It is fine. I am happy this bug is duly treated.
